/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d6da5139be49
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type BulkOnboardNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Not Found
 */
export class BulkOnboardNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: BulkOnboardNotFoundErrorData;

  constructor(
    err: BulkOnboardNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "BulkOnboardNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type BulkOnboardUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Unauthorized
 */
export class BulkOnboardUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: BulkOnboardUnauthorizedErrorData;

  constructor(
    err: BulkOnboardUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "BulkOnboardUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type BulkOnboardBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Bad Request
 */
export class BulkOnboardBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: BulkOnboardBadRequestErrorData;

  constructor(
    err: BulkOnboardBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "BulkOnboardBadRequestError";
  }
}

/** @internal */
export const BulkOnboardNotFoundError$inboundSchema: z.ZodMiniType<
  BulkOnboardNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new BulkOnboardNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const BulkOnboardUnauthorizedError$inboundSchema: z.ZodMiniType<
  BulkOnboardUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new BulkOnboardUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const BulkOnboardBadRequestError$inboundSchema: z.ZodMiniType<
  BulkOnboardBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new BulkOnboardBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
