/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d6bdc510741f
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type CreateProjectNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Not Found
 */
export class CreateProjectNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateProjectNotFoundErrorData;

  constructor(
    err: CreateProjectNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateProjectNotFoundError";
  }
}

/**
 * Forbidden
 */
export type CreateProjectForbiddenErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Forbidden
 */
export class CreateProjectForbiddenError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateProjectForbiddenErrorData;

  constructor(
    err: CreateProjectForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateProjectForbiddenError";
  }
}

/**
 * Payment Required
 */
export type PaymentRequiredErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Payment Required
 */
export class PaymentRequiredError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: PaymentRequiredErrorData;

  constructor(
    err: PaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "PaymentRequiredError";
  }
}

/**
 * Unauthorized
 */
export type CreateProjectUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Unauthorized
 */
export class CreateProjectUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateProjectUnauthorizedErrorData;

  constructor(
    err: CreateProjectUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateProjectUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type CreateProjectBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Bad Request
 */
export class CreateProjectBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateProjectBadRequestErrorData;

  constructor(
    err: CreateProjectBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateProjectBadRequestError";
  }
}

/** @internal */
export const CreateProjectNotFoundError$inboundSchema: z.ZodMiniType<
  CreateProjectNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateProjectNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateProjectForbiddenError$inboundSchema: z.ZodMiniType<
  CreateProjectForbiddenError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateProjectForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const PaymentRequiredError$inboundSchema: z.ZodMiniType<
  PaymentRequiredError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PaymentRequiredError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateProjectUnauthorizedError$inboundSchema: z.ZodMiniType<
  CreateProjectUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateProjectUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateProjectBadRequestError$inboundSchema: z.ZodMiniType<
  CreateProjectBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateProjectBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
