/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5c23420de801
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type CreateEndpointFanoutEventNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Not Found
 */
export class CreateEndpointFanoutEventNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateEndpointFanoutEventNotFoundErrorData;

  constructor(
    err: CreateEndpointFanoutEventNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateEndpointFanoutEventNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type CreateEndpointFanoutEventUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Unauthorized
 */
export class CreateEndpointFanoutEventUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateEndpointFanoutEventUnauthorizedErrorData;

  constructor(
    err: CreateEndpointFanoutEventUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateEndpointFanoutEventUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type CreateEndpointFanoutEventBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Bad Request
 */
export class CreateEndpointFanoutEventBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateEndpointFanoutEventBadRequestErrorData;

  constructor(
    err: CreateEndpointFanoutEventBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateEndpointFanoutEventBadRequestError";
  }
}

/** @internal */
export const CreateEndpointFanoutEventNotFoundError$inboundSchema:
  z.ZodMiniType<CreateEndpointFanoutEventNotFoundError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: types.optional(models.HandlersStub$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new CreateEndpointFanoutEventNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const CreateEndpointFanoutEventUnauthorizedError$inboundSchema:
  z.ZodMiniType<CreateEndpointFanoutEventUnauthorizedError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: types.optional(models.HandlersStub$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new CreateEndpointFanoutEventUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const CreateEndpointFanoutEventBadRequestError$inboundSchema:
  z.ZodMiniType<CreateEndpointFanoutEventBadRequestError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: types.optional(models.HandlersStub$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new CreateEndpointFanoutEventBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
