/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f52b7d678022
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type CreateDynamicEventNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Not Found
 */
export class CreateDynamicEventNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateDynamicEventNotFoundErrorData;

  constructor(
    err: CreateDynamicEventNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateDynamicEventNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type CreateDynamicEventUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Unauthorized
 */
export class CreateDynamicEventUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateDynamicEventUnauthorizedErrorData;

  constructor(
    err: CreateDynamicEventUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateDynamicEventUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type CreateDynamicEventBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Bad Request
 */
export class CreateDynamicEventBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateDynamicEventBadRequestErrorData;

  constructor(
    err: CreateDynamicEventBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "CreateDynamicEventBadRequestError";
  }
}

/** @internal */
export const CreateDynamicEventNotFoundError$inboundSchema: z.ZodMiniType<
  CreateDynamicEventNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateDynamicEventNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateDynamicEventUnauthorizedError$inboundSchema: z.ZodMiniType<
  CreateDynamicEventUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateDynamicEventUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateDynamicEventBadRequestError$inboundSchema: z.ZodMiniType<
  CreateDynamicEventBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateDynamicEventBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
