/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e71a147b6f22
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type ForceResendEventDeliveriesNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Not Found
 */
export class ForceResendEventDeliveriesNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: ForceResendEventDeliveriesNotFoundErrorData;

  constructor(
    err: ForceResendEventDeliveriesNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ForceResendEventDeliveriesNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type ForceResendEventDeliveriesUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Unauthorized
 */
export class ForceResendEventDeliveriesUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: ForceResendEventDeliveriesUnauthorizedErrorData;

  constructor(
    err: ForceResendEventDeliveriesUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ForceResendEventDeliveriesUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type ForceResendEventDeliveriesBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Bad Request
 */
export class ForceResendEventDeliveriesBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: ForceResendEventDeliveriesBadRequestErrorData;

  constructor(
    err: ForceResendEventDeliveriesBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ForceResendEventDeliveriesBadRequestError";
  }
}

/** @internal */
export const ForceResendEventDeliveriesNotFoundError$inboundSchema:
  z.ZodMiniType<ForceResendEventDeliveriesNotFoundError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: types.optional(models.HandlersStub$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ForceResendEventDeliveriesNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ForceResendEventDeliveriesUnauthorizedError$inboundSchema:
  z.ZodMiniType<ForceResendEventDeliveriesUnauthorizedError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: types.optional(models.HandlersStub$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ForceResendEventDeliveriesUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ForceResendEventDeliveriesBadRequestError$inboundSchema:
  z.ZodMiniType<ForceResendEventDeliveriesBadRequestError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: types.optional(models.HandlersStub$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ForceResendEventDeliveriesBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
