/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 518160805d89
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type GetSubscriptionNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Not Found
 */
export class GetSubscriptionNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetSubscriptionNotFoundErrorData;

  constructor(
    err: GetSubscriptionNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetSubscriptionNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type GetSubscriptionUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Unauthorized
 */
export class GetSubscriptionUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetSubscriptionUnauthorizedErrorData;

  constructor(
    err: GetSubscriptionUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetSubscriptionUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type GetSubscriptionBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Bad Request
 */
export class GetSubscriptionBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetSubscriptionBadRequestErrorData;

  constructor(
    err: GetSubscriptionBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetSubscriptionBadRequestError";
  }
}

/** @internal */
export const GetSubscriptionNotFoundError$inboundSchema: z.ZodMiniType<
  GetSubscriptionNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSubscriptionNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSubscriptionUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetSubscriptionUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSubscriptionUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSubscriptionBadRequestError$inboundSchema: z.ZodMiniType<
  GetSubscriptionBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSubscriptionBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
