/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d3230d75ac2
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type GetProjectNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Not Found
 */
export class GetProjectNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetProjectNotFoundErrorData;

  constructor(
    err: GetProjectNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetProjectNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type GetProjectUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Unauthorized
 */
export class GetProjectUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetProjectUnauthorizedErrorData;

  constructor(
    err: GetProjectUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetProjectUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type GetProjectBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Bad Request
 */
export class GetProjectBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetProjectBadRequestErrorData;

  constructor(
    err: GetProjectBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetProjectBadRequestError";
  }
}

/** @internal */
export const GetProjectNotFoundError$inboundSchema: z.ZodMiniType<
  GetProjectNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetProjectNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetProjectUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetProjectUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetProjectUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetProjectBadRequestError$inboundSchema: z.ZodMiniType<
  GetProjectBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetProjectBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
