/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9b672c9fd4c4
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type GetEventDeliveriesPagedNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Not Found
 */
export class GetEventDeliveriesPagedNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetEventDeliveriesPagedNotFoundErrorData;

  constructor(
    err: GetEventDeliveriesPagedNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetEventDeliveriesPagedNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type GetEventDeliveriesPagedUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Unauthorized
 */
export class GetEventDeliveriesPagedUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetEventDeliveriesPagedUnauthorizedErrorData;

  constructor(
    err: GetEventDeliveriesPagedUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetEventDeliveriesPagedUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type GetEventDeliveriesPagedBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Bad Request
 */
export class GetEventDeliveriesPagedBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetEventDeliveriesPagedBadRequestErrorData;

  constructor(
    err: GetEventDeliveriesPagedBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetEventDeliveriesPagedBadRequestError";
  }
}

/** @internal */
export const GetEventDeliveriesPagedNotFoundError$inboundSchema: z.ZodMiniType<
  GetEventDeliveriesPagedNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetEventDeliveriesPagedNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetEventDeliveriesPagedUnauthorizedError$inboundSchema:
  z.ZodMiniType<GetEventDeliveriesPagedUnauthorizedError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: types.optional(models.HandlersStub$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetEventDeliveriesPagedUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetEventDeliveriesPagedBadRequestError$inboundSchema:
  z.ZodMiniType<GetEventDeliveriesPagedBadRequestError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: types.optional(models.HandlersStub$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetEventDeliveriesPagedBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
