/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 539649b0e5cc
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type GetFilterNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Not Found
 */
export class GetFilterNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetFilterNotFoundErrorData;

  constructor(
    err: GetFilterNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetFilterNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type GetFilterUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Unauthorized
 */
export class GetFilterUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetFilterUnauthorizedErrorData;

  constructor(
    err: GetFilterUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetFilterUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type GetFilterBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Bad Request
 */
export class GetFilterBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetFilterBadRequestErrorData;

  constructor(
    err: GetFilterBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetFilterBadRequestError";
  }
}

/** @internal */
export const GetFilterNotFoundError$inboundSchema: z.ZodMiniType<
  GetFilterNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetFilterNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetFilterUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetFilterUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetFilterUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetFilterBadRequestError$inboundSchema: z.ZodMiniType<
  GetFilterBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetFilterBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
