/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 419d5615dfeb
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type GetEndpointEventNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Not Found
 */
export class GetEndpointEventNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetEndpointEventNotFoundErrorData;

  constructor(
    err: GetEndpointEventNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetEndpointEventNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type GetEndpointEventUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Unauthorized
 */
export class GetEndpointEventUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetEndpointEventUnauthorizedErrorData;

  constructor(
    err: GetEndpointEventUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetEndpointEventUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type GetEndpointEventBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Bad Request
 */
export class GetEndpointEventBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetEndpointEventBadRequestErrorData;

  constructor(
    err: GetEndpointEventBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "GetEndpointEventBadRequestError";
  }
}

/** @internal */
export const GetEndpointEventNotFoundError$inboundSchema: z.ZodMiniType<
  GetEndpointEventNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetEndpointEventNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetEndpointEventUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetEndpointEventUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetEndpointEventUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetEndpointEventBadRequestError$inboundSchema: z.ZodMiniType<
  GetEndpointEventBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetEndpointEventBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
