/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4a6e12d9a88a
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type ImportOpenApiSpecNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Not Found
 */
export class ImportOpenApiSpecNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ImportOpenApiSpecNotFoundErrorData;

  constructor(
    err: ImportOpenApiSpecNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ImportOpenApiSpecNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type ImportOpenApiSpecUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Unauthorized
 */
export class ImportOpenApiSpecUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ImportOpenApiSpecUnauthorizedErrorData;

  constructor(
    err: ImportOpenApiSpecUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ImportOpenApiSpecUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type ImportOpenApiSpecBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Bad Request
 */
export class ImportOpenApiSpecBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ImportOpenApiSpecBadRequestErrorData;

  constructor(
    err: ImportOpenApiSpecBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ImportOpenApiSpecBadRequestError";
  }
}

/** @internal */
export const ImportOpenApiSpecNotFoundError$inboundSchema: z.ZodMiniType<
  ImportOpenApiSpecNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ImportOpenApiSpecNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ImportOpenApiSpecUnauthorizedError$inboundSchema: z.ZodMiniType<
  ImportOpenApiSpecUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ImportOpenApiSpecUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ImportOpenApiSpecBadRequestError$inboundSchema: z.ZodMiniType<
  ImportOpenApiSpecBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ImportOpenApiSpecBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
