/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8b33ed77f0c0
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type PauseEndpointNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Not Found
 */
export class PauseEndpointNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: PauseEndpointNotFoundErrorData;

  constructor(
    err: PauseEndpointNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "PauseEndpointNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type PauseEndpointUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Unauthorized
 */
export class PauseEndpointUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: PauseEndpointUnauthorizedErrorData;

  constructor(
    err: PauseEndpointUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "PauseEndpointUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type PauseEndpointBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Bad Request
 */
export class PauseEndpointBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: PauseEndpointBadRequestErrorData;

  constructor(
    err: PauseEndpointBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "PauseEndpointBadRequestError";
  }
}

/** @internal */
export const PauseEndpointNotFoundError$inboundSchema: z.ZodMiniType<
  PauseEndpointNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PauseEndpointNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const PauseEndpointUnauthorizedError$inboundSchema: z.ZodMiniType<
  PauseEndpointUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PauseEndpointUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const PauseEndpointBadRequestError$inboundSchema: z.ZodMiniType<
  PauseEndpointBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PauseEndpointBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
