/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 202c43360be5
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type PostV1ProjectsProjectIDSourcesTestFunctionNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Not Found
 */
export class PostV1ProjectsProjectIDSourcesTestFunctionNotFoundError
  extends ConvoyError
{
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1ProjectsProjectIDSourcesTestFunctionNotFoundErrorData;

  constructor(
    err: PostV1ProjectsProjectIDSourcesTestFunctionNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "PostV1ProjectsProjectIDSourcesTestFunctionNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type PostV1ProjectsProjectIDSourcesTestFunctionUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Unauthorized
 */
export class PostV1ProjectsProjectIDSourcesTestFunctionUnauthorizedError
  extends ConvoyError
{
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1ProjectsProjectIDSourcesTestFunctionUnauthorizedErrorData;

  constructor(
    err: PostV1ProjectsProjectIDSourcesTestFunctionUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "PostV1ProjectsProjectIDSourcesTestFunctionUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type PostV1ProjectsProjectIDSourcesTestFunctionBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Bad Request
 */
export class PostV1ProjectsProjectIDSourcesTestFunctionBadRequestError
  extends ConvoyError
{
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1ProjectsProjectIDSourcesTestFunctionBadRequestErrorData;

  constructor(
    err: PostV1ProjectsProjectIDSourcesTestFunctionBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "PostV1ProjectsProjectIDSourcesTestFunctionBadRequestError";
  }
}

/** @internal */
export const PostV1ProjectsProjectIDSourcesTestFunctionNotFoundError$inboundSchema:
  z.ZodMiniType<
    PostV1ProjectsProjectIDSourcesTestFunctionNotFoundError,
    unknown
  > = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: z.optional(z.nullable(z.record(z.string(), z.any()))),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1ProjectsProjectIDSourcesTestFunctionNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const PostV1ProjectsProjectIDSourcesTestFunctionUnauthorizedError$inboundSchema:
  z.ZodMiniType<
    PostV1ProjectsProjectIDSourcesTestFunctionUnauthorizedError,
    unknown
  > = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: z.optional(z.nullable(z.record(z.string(), z.any()))),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1ProjectsProjectIDSourcesTestFunctionUnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    }),
  );

/** @internal */
export const PostV1ProjectsProjectIDSourcesTestFunctionBadRequestError$inboundSchema:
  z.ZodMiniType<
    PostV1ProjectsProjectIDSourcesTestFunctionBadRequestError,
    unknown
  > = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: z.optional(z.nullable(z.record(z.string(), z.any()))),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1ProjectsProjectIDSourcesTestFunctionBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
