/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbc5d2484050
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type ToggleSubscriptionStatusNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Not Found
 */
export class ToggleSubscriptionStatusNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ToggleSubscriptionStatusNotFoundErrorData;

  constructor(
    err: ToggleSubscriptionStatusNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ToggleSubscriptionStatusNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type ToggleSubscriptionStatusUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Unauthorized
 */
export class ToggleSubscriptionStatusUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ToggleSubscriptionStatusUnauthorizedErrorData;

  constructor(
    err: ToggleSubscriptionStatusUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ToggleSubscriptionStatusUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type ToggleSubscriptionStatusBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/**
 * Bad Request
 */
export class ToggleSubscriptionStatusBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ToggleSubscriptionStatusBadRequestErrorData;

  constructor(
    err: ToggleSubscriptionStatusBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "ToggleSubscriptionStatusBadRequestError";
  }
}

/** @internal */
export const ToggleSubscriptionStatusNotFoundError$inboundSchema: z.ZodMiniType<
  ToggleSubscriptionStatusNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ToggleSubscriptionStatusNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ToggleSubscriptionStatusUnauthorizedError$inboundSchema:
  z.ZodMiniType<ToggleSubscriptionStatusUnauthorizedError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: z.optional(z.nullable(z.record(z.string(), z.any()))),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ToggleSubscriptionStatusUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ToggleSubscriptionStatusBadRequestError$inboundSchema:
  z.ZodMiniType<ToggleSubscriptionStatusBadRequestError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      status: types.optional(types.boolean()),
      data: z.optional(z.nullable(z.record(z.string(), z.any()))),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ToggleSubscriptionStatusBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
