/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2ac13b52909b
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { ConvoyError } from "./convoy-error.js";

/**
 * Not Found
 */
export type UpdateSourceNotFoundErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Not Found
 */
export class UpdateSourceNotFoundError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateSourceNotFoundErrorData;

  constructor(
    err: UpdateSourceNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "UpdateSourceNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type UpdateSourceUnauthorizedErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Unauthorized
 */
export class UpdateSourceUnauthorizedError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateSourceUnauthorizedErrorData;

  constructor(
    err: UpdateSourceUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "UpdateSourceUnauthorizedError";
  }
}

/**
 * Bad Request
 */
export type UpdateSourceBadRequestErrorData = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/**
 * Bad Request
 */
export class UpdateSourceBadRequestError extends ConvoyError {
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateSourceBadRequestErrorData;

  constructor(
    err: UpdateSourceBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.data != null) this.data = err.data;

    this.name = "UpdateSourceBadRequestError";
  }
}

/** @internal */
export const UpdateSourceNotFoundError$inboundSchema: z.ZodMiniType<
  UpdateSourceNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UpdateSourceNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UpdateSourceUnauthorizedError$inboundSchema: z.ZodMiniType<
  UpdateSourceUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UpdateSourceUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UpdateSourceBadRequestError$inboundSchema: z.ZodMiniType<
  UpdateSourceBadRequestError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    status: types.optional(types.boolean()),
    data: types.optional(models.HandlersStub$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UpdateSourceBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
