/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a2fee73b99a
 */

import * as z from "zod/v4-mini";
import { ConvoyCore } from "../core.js";
import { encodeSimple } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { ConvoyError } from "../models/errors/convoy-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Deprecates an event type
 *
 * @remarks
 * This endpoint deprecates an event type
 */
export function eventTypesDeprecateEventType(
  client: ConvoyCore,
  projectID: string,
  eventTypeId: string,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.DeprecateEventTypeResponse,
    | errors.DeprecateEventTypeBadRequestError
    | errors.DeprecateEventTypeUnauthorizedError
    | errors.DeprecateEventTypeNotFoundError
    | ConvoyError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    projectID,
    eventTypeId,
    options,
  ));
}

async function $do(
  client: ConvoyCore,
  projectID: string,
  eventTypeId: string,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.DeprecateEventTypeResponse,
      | errors.DeprecateEventTypeBadRequestError
      | errors.DeprecateEventTypeUnauthorizedError
      | errors.DeprecateEventTypeNotFoundError
      | ConvoyError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const input: operations.DeprecateEventTypeRequest = {
    projectID: projectID,
    eventTypeId: eventTypeId,
  };

  const parsed = safeParse(
    input,
    (value) =>
      z.parse(operations.DeprecateEventTypeRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const pathParams = {
    eventTypeId: encodeSimple("eventTypeId", payload.eventTypeId, {
      explode: false,
      charEncoding: "percent",
    }),
    projectID: encodeSimple("projectID", payload.projectID, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path = pathToFunc(
    "/v1/projects/{projectID}/event-types/{eventTypeId}/deprecate",
  )(pathParams);

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKeyAuth);
  const securityInput = secConfig == null ? {} : { apiKeyAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "DeprecateEventType",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKeyAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.DeprecateEventTypeResponse,
    | errors.DeprecateEventTypeBadRequestError
    | errors.DeprecateEventTypeUnauthorizedError
    | errors.DeprecateEventTypeNotFoundError
    | ConvoyError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(201, operations.DeprecateEventTypeResponse$inboundSchema),
    M.jsonErr(400, errors.DeprecateEventTypeBadRequestError$inboundSchema),
    M.jsonErr(401, errors.DeprecateEventTypeUnauthorizedError$inboundSchema),
    M.jsonErr(404, errors.DeprecateEventTypeNotFoundError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
