/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 37917a4b648c
 */

import * as z from "zod/v4-mini";
import { ConvoyCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { ConvoyError } from "../models/errors/convoy-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Bulk onboard endpoints with subscriptions
 *
 * @remarks
 * This endpoint accepts a CSV file or JSON body to bulk-create endpoints with subscriptions
 */
export function onboardBulkOnboard(
  client: ConvoyCore,
  projectID: string,
  dryRun?: boolean | undefined,
  body?:
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Uint8Array
    | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.BulkOnboardResponse,
    | errors.BulkOnboardBadRequestError
    | errors.BulkOnboardUnauthorizedError
    | errors.BulkOnboardNotFoundError
    | ConvoyError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    projectID,
    dryRun,
    body,
    options,
  ));
}

async function $do(
  client: ConvoyCore,
  projectID: string,
  dryRun?: boolean | undefined,
  body?:
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Uint8Array
    | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.BulkOnboardResponse,
      | errors.BulkOnboardBadRequestError
      | errors.BulkOnboardUnauthorizedError
      | errors.BulkOnboardNotFoundError
      | ConvoyError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const input: operations.BulkOnboardRequest = {
    projectID: projectID,
    dryRun: dryRun,
    body: body,
  };

  const parsed = safeParse(
    input,
    (value) => z.parse(operations.BulkOnboardRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body$ = payload.body instanceof Uint8Array
    ? new Uint8Array(payload.body).buffer
    : payload.body;

  const pathParams = {
    projectID: encodeSimple("projectID", payload.projectID, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path = pathToFunc("/v1/projects/{projectID}/onboard")(pathParams);

  const query = encodeFormQuery({
    "dry_run": payload.dry_run,
  });

  const headers = new Headers(compactMap({
    "Content-Type": "application/octet-stream",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKeyAuth);
  const securityInput = secConfig == null ? {} : { apiKeyAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "BulkOnboard",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKeyAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body$,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.BulkOnboardResponse,
    | errors.BulkOnboardBadRequestError
    | errors.BulkOnboardUnauthorizedError
    | errors.BulkOnboardNotFoundError
    | ConvoyError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.BulkOnboardResponse$inboundSchema),
    M.json(202, operations.BulkOnboardResponse$inboundSchema),
    M.jsonErr(400, errors.BulkOnboardBadRequestError$inboundSchema),
    M.jsonErr(401, errors.BulkOnboardUnauthorizedError$inboundSchema),
    M.jsonErr(404, errors.BulkOnboardNotFoundError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
