/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 28db99a2758b
 */

import * as z from "zod/v4-mini";
import { ConvoyCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { ConvoyError } from "../models/errors/convoy-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Update a subscription
 *
 * @remarks
 * This endpoint updates a subscription
 */
export function subscriptionsUpdateSubscription(
  client: ConvoyCore,
  projectID: string,
  subscriptionID: string,
  body: models.ModelsUpdateSubscription,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.UpdateSubscriptionResponse,
    | errors.UpdateSubscriptionBadRequestError
    | errors.UpdateSubscriptionUnauthorizedError
    | errors.UpdateSubscriptionNotFoundError
    | ConvoyError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    projectID,
    subscriptionID,
    body,
    options,
  ));
}

async function $do(
  client: ConvoyCore,
  projectID: string,
  subscriptionID: string,
  body: models.ModelsUpdateSubscription,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.UpdateSubscriptionResponse,
      | errors.UpdateSubscriptionBadRequestError
      | errors.UpdateSubscriptionUnauthorizedError
      | errors.UpdateSubscriptionNotFoundError
      | ConvoyError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const input: operations.UpdateSubscriptionRequest = {
    projectID: projectID,
    subscriptionID: subscriptionID,
    body: body,
  };

  const parsed = safeParse(
    input,
    (value) =>
      z.parse(operations.UpdateSubscriptionRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body$ = encodeJSON("body", payload.body, { explode: true });

  const pathParams = {
    projectID: encodeSimple("projectID", payload.projectID, {
      explode: false,
      charEncoding: "percent",
    }),
    subscriptionID: encodeSimple("subscriptionID", payload.subscriptionID, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path = pathToFunc(
    "/v1/projects/{projectID}/subscriptions/{subscriptionID}",
  )(pathParams);

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKeyAuth);
  const securityInput = secConfig == null ? {} : { apiKeyAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "UpdateSubscription",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKeyAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "PUT",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body$,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.UpdateSubscriptionResponse,
    | errors.UpdateSubscriptionBadRequestError
    | errors.UpdateSubscriptionUnauthorizedError
    | errors.UpdateSubscriptionNotFoundError
    | ConvoyError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(202, operations.UpdateSubscriptionResponse$inboundSchema),
    M.jsonErr(400, errors.UpdateSubscriptionBadRequestError$inboundSchema),
    M.jsonErr(401, errors.UpdateSubscriptionUnauthorizedError$inboundSchema),
    M.jsonErr(404, errors.UpdateSubscriptionNotFoundError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
