/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4fef1ea742e0
 */

import { deliveryAttemptsGetDeliveryAttempt } from "../funcs/delivery-attempts-get-delivery-attempt.js";
import { deliveryAttemptsGetDeliveryAttempts } from "../funcs/delivery-attempts-get-delivery-attempts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DeliveryAttempts extends ClientSDK {
  /**
   * List delivery attempts
   *
   * @remarks
   * This endpoint fetches an app message's delivery attempts
   */
  async getDeliveryAttempts(
    projectID: string,
    eventDeliveryID: string,
    options?: RequestOptions,
  ): Promise<operations.GetDeliveryAttemptsResponse> {
    return unwrapAsync(deliveryAttemptsGetDeliveryAttempts(
      this,
      projectID,
      eventDeliveryID,
      options,
    ));
  }

  /**
   * Retrieve a delivery attempt
   *
   * @remarks
   * This endpoint fetches an app event delivery attempt
   */
  async getDeliveryAttempt(
    projectID: string,
    eventDeliveryID: string,
    deliveryAttemptID: string,
    options?: RequestOptions,
  ): Promise<operations.GetDeliveryAttemptResponse> {
    return unwrapAsync(deliveryAttemptsGetDeliveryAttempt(
      this,
      projectID,
      eventDeliveryID,
      deliveryAttemptID,
      options,
    ));
  }
}
