/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c7d130088b17
 */

import { eventsBatchReplayEvents } from "../funcs/events-batch-replay-events.js";
import { eventsCountAffectedEvents } from "../funcs/events-count-affected-events.js";
import { eventsCreateBroadcastEvent } from "../funcs/events-create-broadcast-event.js";
import { eventsCreateDynamicEvent } from "../funcs/events-create-dynamic-event.js";
import { eventsCreateEndpointEvent } from "../funcs/events-create-endpoint-event.js";
import { eventsCreateEndpointFanoutEvent } from "../funcs/events-create-endpoint-fanout-event.js";
import { eventsGetEndpointEvent } from "../funcs/events-get-endpoint-event.js";
import { eventsGetEventsPaged } from "../funcs/events-get-events-paged.js";
import { eventsReplayEndpointEvent } from "../funcs/events-replay-endpoint-event.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Events extends ClientSDK {
  /**
   * List all events
   *
   * @remarks
   * This endpoint fetches app events with pagination
   */
  async getEventsPaged(
    request: operations.GetEventsPagedRequest,
    options?: RequestOptions,
  ): Promise<operations.GetEventsPagedResponse> {
    return unwrapAsync(eventsGetEventsPaged(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an event
   *
   * @remarks
   * This endpoint creates an endpoint event
   */
  async createEndpointEvent(
    projectID: string,
    body: models.ModelsCreateEvent,
    options?: RequestOptions,
  ): Promise<operations.CreateEndpointEventResponse> {
    return unwrapAsync(eventsCreateEndpointEvent(
      this,
      projectID,
      body,
      options,
    ));
  }

  /**
   * Batch replay events
   *
   * @remarks
   * This endpoint replays multiple events at once.
   */
  async batchReplayEvents(
    request: operations.BatchReplayEventsRequest,
    options?: RequestOptions,
  ): Promise<operations.BatchReplayEventsResponse> {
    return unwrapAsync(eventsBatchReplayEvents(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a broadcast event
   *
   * @remarks
   * This endpoint creates a event that is broadcast to every endpoint whose subscription matches the given event type.
   */
  async createBroadcastEvent(
    projectID: string,
    body: models.ModelsBroadcastEvent,
    options?: RequestOptions,
  ): Promise<operations.CreateBroadcastEventResponse> {
    return unwrapAsync(eventsCreateBroadcastEvent(
      this,
      projectID,
      body,
      options,
    ));
  }

  /**
   * Count events matching batch replay filters
   *
   * @remarks
   * This endpoint returns how many events would be affected by a batch replay with the given filters.
   */
  async countAffectedEvents(
    request: operations.CountAffectedEventsRequest,
    options?: RequestOptions,
  ): Promise<operations.CountAffectedEventsResponse> {
    return unwrapAsync(eventsCountAffectedEvents(
      this,
      request,
      options,
    ));
  }

  /**
   * Dynamic Events
   *
   * @remarks
   * This endpoint does not require creating endpoint and subscriptions ahead of time. Instead, you supply the endpoint and the payload, and Convoy delivers the events
   */
  async createDynamicEvent(
    projectID: string,
    body: models.ModelsDynamicEvent,
    options?: RequestOptions,
  ): Promise<operations.CreateDynamicEventResponse> {
    return unwrapAsync(eventsCreateDynamicEvent(
      this,
      projectID,
      body,
      options,
    ));
  }

  /**
   * Fan out an event
   *
   * @remarks
   * This endpoint uses the owner_id to fan out an event to multiple endpoints.
   */
  async createEndpointFanoutEvent(
    projectID: string,
    body: models.ModelsFanoutEvent,
    options?: RequestOptions,
  ): Promise<operations.CreateEndpointFanoutEventResponse> {
    return unwrapAsync(eventsCreateEndpointFanoutEvent(
      this,
      projectID,
      body,
      options,
    ));
  }

  /**
   * Retrieve an event
   *
   * @remarks
   * This endpoint retrieves an event
   */
  async getEndpointEvent(
    projectID: string,
    eventID: string,
    options?: RequestOptions,
  ): Promise<operations.GetEndpointEventResponse> {
    return unwrapAsync(eventsGetEndpointEvent(
      this,
      projectID,
      eventID,
      options,
    ));
  }

  /**
   * Replay event
   *
   * @remarks
   * This endpoint replays an event afresh assuming it is a new event.
   */
  async replayEndpointEvent(
    projectID: string,
    eventID: string,
    options?: RequestOptions,
  ): Promise<operations.ReplayEndpointEventResponse> {
    return unwrapAsync(eventsReplayEndpointEvent(
      this,
      projectID,
      eventID,
      options,
    ));
  }
}
