/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 47097667caa2
 */

import { onboardBulkOnboard } from "../funcs/onboard-bulk-onboard.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Onboard extends ClientSDK {
  /**
   * Bulk onboard endpoints with subscriptions
   *
   * @remarks
   * This endpoint accepts a CSV file or JSON body to bulk-create endpoints with subscriptions
   */
  async bulkOnboard(
    projectID: string,
    dryRun?: boolean | undefined,
    body?:
      | ReadableStream<Uint8Array>
      | Blob
      | ArrayBuffer
      | Uint8Array
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.BulkOnboardResponse> {
    return unwrapAsync(onboardBulkOnboard(
      this,
      projectID,
      dryRun,
      body,
      options,
    ));
  }
}
