/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 28088373a118
 */

import { projectsCreateProject } from "../funcs/projects-create-project.js";
import { projectsDeleteProject } from "../funcs/projects-delete-project.js";
import { projectsGetProject } from "../funcs/projects-get-project.js";
import { projectsGetProjects } from "../funcs/projects-get-projects.js";
import { projectsUpdateProject } from "../funcs/projects-update-project.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * List all projects
   *
   * @remarks
   * This endpoint fetches projects for an organisation. Authenticate with a personal API key or JWT and pass the organisation id as the orgID query parameter.
   */
  async getProjects(
    orgID: string,
    options?: RequestOptions,
  ): Promise<operations.GetProjectsResponse> {
    return unwrapAsync(projectsGetProjects(
      this,
      orgID,
      options,
    ));
  }

  /**
   * Create a project
   *
   * @remarks
   * This endpoint creates a project. Authenticate with a personal API key or JWT and pass the organisation id as the orgID query parameter. The response includes the project and a one-time project API key.
   */
  async createProject(
    orgID: string,
    body: models.ModelsCreateProject,
    options?: RequestOptions,
  ): Promise<operations.CreateProjectResponse> {
    return unwrapAsync(projectsCreateProject(
      this,
      orgID,
      body,
      options,
    ));
  }

  /**
   * Delete a project
   *
   * @remarks
   * This endpoint deletes a project
   */
  async deleteProject(
    projectID: string,
    options?: RequestOptions,
  ): Promise<operations.DeleteProjectResponse> {
    return unwrapAsync(projectsDeleteProject(
      this,
      projectID,
      options,
    ));
  }

  /**
   * Retrieve a project
   *
   * @remarks
   * This endpoint fetches a project by its id
   */
  async getProject(
    projectID: string,
    options?: RequestOptions,
  ): Promise<operations.GetProjectResponse> {
    return unwrapAsync(projectsGetProject(
      this,
      projectID,
      options,
    ));
  }

  /**
   * Update a project
   *
   * @remarks
   * This endpoint updates a project's name, logo, and config
   */
  async updateProject(
    projectID: string,
    body: models.ModelsUpdateProject,
    options?: RequestOptions,
  ): Promise<operations.UpdateProjectResponse> {
    return unwrapAsync(projectsUpdateProject(
      this,
      projectID,
      body,
      options,
    ));
  }
}
