/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0d496d611249
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the convoy.js SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx projectsGetProjects.example.ts
 */

import { Convoy } from "convoy.js";

const convoy = new Convoy({
  apiKeyAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await convoy.projects.getProjects("<id>");

  console.log(result);
}

main().catch(console.error);
