/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 77b8ff3ab1ff
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ActivateEndpointRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Endpoint ID
   */
  endpointID: string;
};

/**
 * Accepted
 */
export type ActivateEndpointResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsEndpointResponse | undefined;
};

/** @internal */
export type ActivateEndpointRequest$Outbound = {
  projectID: string;
  endpointID: string;
};

/** @internal */
export const ActivateEndpointRequest$outboundSchema: z.ZodMiniType<
  ActivateEndpointRequest$Outbound,
  ActivateEndpointRequest
> = z.object({
  projectID: z.string(),
  endpointID: z.string(),
});

export function activateEndpointRequestToJSON(
  activateEndpointRequest: ActivateEndpointRequest,
): string {
  return JSON.stringify(
    ActivateEndpointRequest$outboundSchema.parse(activateEndpointRequest),
  );
}

/** @internal */
export const ActivateEndpointResponse$inboundSchema: z.ZodMiniType<
  ActivateEndpointResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsEndpointResponse$inboundSchema),
});

export function activateEndpointResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActivateEndpointResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivateEndpointResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivateEndpointResponse' from JSON`,
  );
}
