/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d2e50d9d9087
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type BulkOnboardRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Validate without creating
   */
  dryRun?: boolean | undefined;
  /**
   * Onboard Details (JSON)
   */
  body?: models.ModelsBulkOnboardRequest | undefined;
};

/**
 * Accepted
 */
export type BulkOnboardResponseBody2 = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsBulkOnboardAcceptedResponse | undefined;
};

/**
 * OK
 */
export type BulkOnboardResponseBody1 = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsBulkOnboardDryRunResponse | undefined;
};

export type BulkOnboardResponse =
  | BulkOnboardResponseBody1
  | BulkOnboardResponseBody2;

/** @internal */
export type BulkOnboardRequest$Outbound = {
  projectID: string;
  dry_run?: boolean | undefined;
  body?: models.ModelsBulkOnboardRequest$Outbound | undefined;
};

/** @internal */
export const BulkOnboardRequest$outboundSchema: z.ZodMiniType<
  BulkOnboardRequest$Outbound,
  BulkOnboardRequest
> = z.pipe(
  z.object({
    projectID: z.string(),
    dryRun: z.optional(z.boolean()),
    body: z.optional(models.ModelsBulkOnboardRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      dryRun: "dry_run",
    });
  }),
);

export function bulkOnboardRequestToJSON(
  bulkOnboardRequest: BulkOnboardRequest,
): string {
  return JSON.stringify(
    BulkOnboardRequest$outboundSchema.parse(bulkOnboardRequest),
  );
}

/** @internal */
export const BulkOnboardResponseBody2$inboundSchema: z.ZodMiniType<
  BulkOnboardResponseBody2,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsBulkOnboardAcceptedResponse$inboundSchema),
});

export function bulkOnboardResponseBody2FromJSON(
  jsonString: string,
): SafeParseResult<BulkOnboardResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkOnboardResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkOnboardResponseBody2' from JSON`,
  );
}

/** @internal */
export const BulkOnboardResponseBody1$inboundSchema: z.ZodMiniType<
  BulkOnboardResponseBody1,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsBulkOnboardDryRunResponse$inboundSchema),
});

export function bulkOnboardResponseBody1FromJSON(
  jsonString: string,
): SafeParseResult<BulkOnboardResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkOnboardResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkOnboardResponseBody1' from JSON`,
  );
}

/** @internal */
export const BulkOnboardResponse$inboundSchema: z.ZodMiniType<
  BulkOnboardResponse,
  unknown
> = smartUnion([
  z.lazy(() => BulkOnboardResponseBody1$inboundSchema),
  z.lazy(() => BulkOnboardResponseBody2$inboundSchema),
]);

export function bulkOnboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkOnboardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkOnboardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkOnboardResponse' from JSON`,
  );
}
