/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2a735e9e00ac
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type BulkUpdateFiltersRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Subscription ID
   */
  subscriptionID: string;
  /**
   * Filters to update
   */
  body: Array<models.ModelsBulkUpdateFilterRequest>;
};

/**
 * OK
 */
export type BulkUpdateFiltersResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<models.ModelsFilterResponse> | undefined;
};

/** @internal */
export type BulkUpdateFiltersRequest$Outbound = {
  projectID: string;
  subscriptionID: string;
  body: Array<models.ModelsBulkUpdateFilterRequest$Outbound>;
};

/** @internal */
export const BulkUpdateFiltersRequest$outboundSchema: z.ZodMiniType<
  BulkUpdateFiltersRequest$Outbound,
  BulkUpdateFiltersRequest
> = z.object({
  projectID: z.string(),
  subscriptionID: z.string(),
  body: z.array(models.ModelsBulkUpdateFilterRequest$outboundSchema),
});

export function bulkUpdateFiltersRequestToJSON(
  bulkUpdateFiltersRequest: BulkUpdateFiltersRequest,
): string {
  return JSON.stringify(
    BulkUpdateFiltersRequest$outboundSchema.parse(bulkUpdateFiltersRequest),
  );
}

/** @internal */
export const BulkUpdateFiltersResponse$inboundSchema: z.ZodMiniType<
  BulkUpdateFiltersResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.array(models.ModelsFilterResponse$inboundSchema)),
});

export function bulkUpdateFiltersResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkUpdateFiltersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkUpdateFiltersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdateFiltersResponse' from JSON`,
  );
}
