/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cc3125316a32
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateSourceRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Source Details
   */
  body: models.ModelsCreateSource;
};

/**
 * Created
 */
export type CreateSourceResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsSourceResponse | undefined;
};

/** @internal */
export type CreateSourceRequest$Outbound = {
  projectID: string;
  body: models.ModelsCreateSource$Outbound;
};

/** @internal */
export const CreateSourceRequest$outboundSchema: z.ZodMiniType<
  CreateSourceRequest$Outbound,
  CreateSourceRequest
> = z.object({
  projectID: z.string(),
  body: models.ModelsCreateSource$outboundSchema,
});

export function createSourceRequestToJSON(
  createSourceRequest: CreateSourceRequest,
): string {
  return JSON.stringify(
    CreateSourceRequest$outboundSchema.parse(createSourceRequest),
  );
}

/** @internal */
export const CreateSourceResponse$inboundSchema: z.ZodMiniType<
  CreateSourceResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsSourceResponse$inboundSchema),
});

export function createSourceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSourceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSourceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSourceResponse' from JSON`,
  );
}
