/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f8a2e967090e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBroadcastEventRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Broadcast Event Details
   */
  body: models.ModelsBroadcastEvent;
};

/**
 * Created
 */
export type CreateBroadcastEventResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsEventResponse | undefined;
};

/** @internal */
export type CreateBroadcastEventRequest$Outbound = {
  projectID: string;
  body: models.ModelsBroadcastEvent$Outbound;
};

/** @internal */
export const CreateBroadcastEventRequest$outboundSchema: z.ZodMiniType<
  CreateBroadcastEventRequest$Outbound,
  CreateBroadcastEventRequest
> = z.object({
  projectID: z.string(),
  body: models.ModelsBroadcastEvent$outboundSchema,
});

export function createBroadcastEventRequestToJSON(
  createBroadcastEventRequest: CreateBroadcastEventRequest,
): string {
  return JSON.stringify(
    CreateBroadcastEventRequest$outboundSchema.parse(
      createBroadcastEventRequest,
    ),
  );
}

/** @internal */
export const CreateBroadcastEventResponse$inboundSchema: z.ZodMiniType<
  CreateBroadcastEventResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsEventResponse$inboundSchema),
});

export function createBroadcastEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBroadcastEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBroadcastEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBroadcastEventResponse' from JSON`,
  );
}
