/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c5e1aa6ba56e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateProjectRequest = {
  /**
   * Organisation ID
   */
  orgID: string;
  /**
   * Project Details
   */
  body: models.ModelsCreateProject;
};

/**
 * Created
 */
export type CreateProjectResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsCreateProjectResponse | undefined;
};

/** @internal */
export type CreateProjectRequest$Outbound = {
  orgID: string;
  body: models.ModelsCreateProject$Outbound;
};

/** @internal */
export const CreateProjectRequest$outboundSchema: z.ZodMiniType<
  CreateProjectRequest$Outbound,
  CreateProjectRequest
> = z.object({
  orgID: z.string(),
  body: models.ModelsCreateProject$outboundSchema,
});

export function createProjectRequestToJSON(
  createProjectRequest: CreateProjectRequest,
): string {
  return JSON.stringify(
    CreateProjectRequest$outboundSchema.parse(createProjectRequest),
  );
}

/** @internal */
export const CreateProjectResponse$inboundSchema: z.ZodMiniType<
  CreateProjectResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsCreateProjectResponse$inboundSchema),
});

export function createProjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateProjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProjectResponse' from JSON`,
  );
}
