/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4409dfb250dc
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePortalLinkRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Portal Link Details
   */
  body: models.DatastoreCreatePortalLinkRequest;
};

/**
 * Created
 */
export type CreatePortalLinkResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.DatastorePortalLinkResponse | undefined;
};

/** @internal */
export type CreatePortalLinkRequest$Outbound = {
  projectID: string;
  body: models.DatastoreCreatePortalLinkRequest$Outbound;
};

/** @internal */
export const CreatePortalLinkRequest$outboundSchema: z.ZodMiniType<
  CreatePortalLinkRequest$Outbound,
  CreatePortalLinkRequest
> = z.object({
  projectID: z.string(),
  body: models.DatastoreCreatePortalLinkRequest$outboundSchema,
});

export function createPortalLinkRequestToJSON(
  createPortalLinkRequest: CreatePortalLinkRequest,
): string {
  return JSON.stringify(
    CreatePortalLinkRequest$outboundSchema.parse(createPortalLinkRequest),
  );
}

/** @internal */
export const CreatePortalLinkResponse$inboundSchema: z.ZodMiniType<
  CreatePortalLinkResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.DatastorePortalLinkResponse$inboundSchema),
});

export function createPortalLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePortalLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePortalLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePortalLinkResponse' from JSON`,
  );
}
