/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a8756b83fa4c
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateEndpointFanoutEventRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Event Details
   */
  body: models.ModelsFanoutEvent;
};

/**
 * Created
 */
export type CreateEndpointFanoutEventResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/** @internal */
export type CreateEndpointFanoutEventRequest$Outbound = {
  projectID: string;
  body: models.ModelsFanoutEvent$Outbound;
};

/** @internal */
export const CreateEndpointFanoutEventRequest$outboundSchema: z.ZodMiniType<
  CreateEndpointFanoutEventRequest$Outbound,
  CreateEndpointFanoutEventRequest
> = z.object({
  projectID: z.string(),
  body: models.ModelsFanoutEvent$outboundSchema,
});

export function createEndpointFanoutEventRequestToJSON(
  createEndpointFanoutEventRequest: CreateEndpointFanoutEventRequest,
): string {
  return JSON.stringify(
    CreateEndpointFanoutEventRequest$outboundSchema.parse(
      createEndpointFanoutEventRequest,
    ),
  );
}

/** @internal */
export const CreateEndpointFanoutEventResponse$inboundSchema: z.ZodMiniType<
  CreateEndpointFanoutEventResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.HandlersStub$inboundSchema),
});

export function createEndpointFanoutEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateEndpointFanoutEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateEndpointFanoutEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateEndpointFanoutEventResponse' from JSON`,
  );
}
