/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 66f147dc1432
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteSubscriptionRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * subscription id
   */
  subscriptionID: string;
};

/**
 * OK
 */
export type DeleteSubscriptionResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: { [k: string]: any } | null | undefined;
};

/** @internal */
export type DeleteSubscriptionRequest$Outbound = {
  projectID: string;
  subscriptionID: string;
};

/** @internal */
export const DeleteSubscriptionRequest$outboundSchema: z.ZodMiniType<
  DeleteSubscriptionRequest$Outbound,
  DeleteSubscriptionRequest
> = z.object({
  projectID: z.string(),
  subscriptionID: z.string(),
});

export function deleteSubscriptionRequestToJSON(
  deleteSubscriptionRequest: DeleteSubscriptionRequest,
): string {
  return JSON.stringify(
    DeleteSubscriptionRequest$outboundSchema.parse(deleteSubscriptionRequest),
  );
}

/** @internal */
export const DeleteSubscriptionResponse$inboundSchema: z.ZodMiniType<
  DeleteSubscriptionResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: z.optional(z.nullable(z.record(z.string(), z.any()))),
});

export function deleteSubscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSubscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSubscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSubscriptionResponse' from JSON`,
  );
}
