/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5df25a33553b
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ExpireSecretRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Endpoint ID
   */
  endpointID: string;
  /**
   * Expire Secret Body Parameters
   */
  body: models.ModelsExpireSecret;
};

/**
 * OK
 */
export type ExpireSecretResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsEndpointResponse | undefined;
};

/** @internal */
export type ExpireSecretRequest$Outbound = {
  projectID: string;
  endpointID: string;
  body: models.ModelsExpireSecret$Outbound;
};

/** @internal */
export const ExpireSecretRequest$outboundSchema: z.ZodMiniType<
  ExpireSecretRequest$Outbound,
  ExpireSecretRequest
> = z.object({
  projectID: z.string(),
  endpointID: z.string(),
  body: models.ModelsExpireSecret$outboundSchema,
});

export function expireSecretRequestToJSON(
  expireSecretRequest: ExpireSecretRequest,
): string {
  return JSON.stringify(
    ExpireSecretRequest$outboundSchema.parse(expireSecretRequest),
  );
}

/** @internal */
export const ExpireSecretResponse$inboundSchema: z.ZodMiniType<
  ExpireSecretResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsEndpointResponse$inboundSchema),
});

export function expireSecretResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExpireSecretResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpireSecretResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpireSecretResponse' from JSON`,
  );
}
