/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e3f7b49e79b
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetEventDeliveryRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * event delivery id
   */
  eventDeliveryID: string;
};

/**
 * OK
 */
export type GetEventDeliveryResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsEventDeliveryResponse | undefined;
};

/** @internal */
export type GetEventDeliveryRequest$Outbound = {
  projectID: string;
  eventDeliveryID: string;
};

/** @internal */
export const GetEventDeliveryRequest$outboundSchema: z.ZodMiniType<
  GetEventDeliveryRequest$Outbound,
  GetEventDeliveryRequest
> = z.object({
  projectID: z.string(),
  eventDeliveryID: z.string(),
});

export function getEventDeliveryRequestToJSON(
  getEventDeliveryRequest: GetEventDeliveryRequest,
): string {
  return JSON.stringify(
    GetEventDeliveryRequest$outboundSchema.parse(getEventDeliveryRequest),
  );
}

/** @internal */
export const GetEventDeliveryResponse$inboundSchema: z.ZodMiniType<
  GetEventDeliveryResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsEventDeliveryResponse$inboundSchema),
});

export function getEventDeliveryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetEventDeliveryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventDeliveryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventDeliveryResponse' from JSON`,
  );
}
