/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dcc6a3540a5f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const GetEndpointsDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type GetEndpointsDirection = ClosedEnum<typeof GetEndpointsDirection>;

export type GetEndpointsRequest = {
  /**
   * Project ID
   */
  projectID: string;
  direction?: GetEndpointsDirection | undefined;
  /**
   * A pagination cursor to fetch the next page of a list
   */
  nextPageCursor?: string | undefined;
  /**
   * The owner ID of the endpoint
   */
  ownerId?: string | undefined;
  /**
   * The number of items to return per page
   */
  perPage?: number | undefined;
  /**
   * A pagination cursor to fetch the previous page of a list
   */
  prevPageCursor?: string | undefined;
  /**
   * The name of the endpoint
   */
  q?: string | undefined;
  /**
   * Sort order, values are `ASC` or `DESC`, defaults to `DESC`
   */
  sort?: string | undefined;
};

export type GetEndpointsPagination = {
  hasNextPage?: boolean | undefined;
  hasPrevPage?: boolean | undefined;
  nextPageCursor?: string | undefined;
  perPage?: number | undefined;
  prevPageCursor?: string | undefined;
  total?: number | undefined;
};

export type GetEndpointsData = {
  content?: Array<models.ModelsEndpointResponse> | undefined;
  pagination?: GetEndpointsPagination | null | undefined;
};

/**
 * OK
 */
export type GetEndpointsResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: GetEndpointsData | undefined;
};

/** @internal */
export const GetEndpointsDirection$outboundSchema: z.ZodMiniEnum<
  typeof GetEndpointsDirection
> = z.enum(GetEndpointsDirection);

/** @internal */
export type GetEndpointsRequest$Outbound = {
  projectID: string;
  direction?: string | undefined;
  next_page_cursor?: string | undefined;
  ownerId?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  q?: string | undefined;
  sort?: string | undefined;
};

/** @internal */
export const GetEndpointsRequest$outboundSchema: z.ZodMiniType<
  GetEndpointsRequest$Outbound,
  GetEndpointsRequest
> = z.pipe(
  z.object({
    projectID: z.string(),
    direction: z.optional(GetEndpointsDirection$outboundSchema),
    nextPageCursor: z.optional(z.string()),
    ownerId: z.optional(z.string()),
    perPage: z.optional(z.int()),
    prevPageCursor: z.optional(z.string()),
    q: z.optional(z.string()),
    sort: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      nextPageCursor: "next_page_cursor",
      prevPageCursor: "prev_page_cursor",
    });
  }),
);

export function getEndpointsRequestToJSON(
  getEndpointsRequest: GetEndpointsRequest,
): string {
  return JSON.stringify(
    GetEndpointsRequest$outboundSchema.parse(getEndpointsRequest),
  );
}

/** @internal */
export const GetEndpointsPagination$inboundSchema: z.ZodMiniType<
  GetEndpointsPagination,
  unknown
> = z.pipe(
  z.object({
    has_next_page: types.optional(types.boolean()),
    has_prev_page: types.optional(types.boolean()),
    next_page_cursor: types.optional(types.string()),
    per_page: types.optional(types.number()),
    prev_page_cursor: types.optional(types.string()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_next_page": "hasNextPage",
      "has_prev_page": "hasPrevPage",
      "next_page_cursor": "nextPageCursor",
      "per_page": "perPage",
      "prev_page_cursor": "prevPageCursor",
    });
  }),
);

export function getEndpointsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetEndpointsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEndpointsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEndpointsPagination' from JSON`,
  );
}

/** @internal */
export const GetEndpointsData$inboundSchema: z.ZodMiniType<
  GetEndpointsData,
  unknown
> = z.object({
  content: types.optional(z.array(models.ModelsEndpointResponse$inboundSchema)),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetEndpointsPagination$inboundSchema)),
  ),
});

export function getEndpointsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetEndpointsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEndpointsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEndpointsData' from JSON`,
  );
}

/** @internal */
export const GetEndpointsResponse$inboundSchema: z.ZodMiniType<
  GetEndpointsResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.lazy(() => GetEndpointsData$inboundSchema)),
});

export function getEndpointsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetEndpointsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEndpointsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEndpointsResponse' from JSON`,
  );
}
