/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a17b720aa23
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const GetSubscriptionsDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type GetSubscriptionsDirection = ClosedEnum<
  typeof GetSubscriptionsDirection
>;

export type GetSubscriptionsRequest = {
  /**
   * Project ID
   */
  projectID: string;
  direction?: GetSubscriptionsDirection | undefined;
  /**
   * A list of endpointIDs to filter by
   */
  endpointId?: Array<string> | undefined;
  /**
   * Subscription name to filter by
   */
  name?: string | undefined;
  /**
   * A pagination cursor to fetch the next page of a list
   */
  nextPageCursor?: string | undefined;
  /**
   * The number of items to return per page
   */
  perPage?: number | undefined;
  /**
   * A pagination cursor to fetch the previous page of a list
   */
  prevPageCursor?: string | undefined;
  /**
   * Sort order, values are `ASC` or `DESC`, defaults to `DESC`
   */
  sort?: string | undefined;
};

export type GetSubscriptionsPagination = {
  hasNextPage?: boolean | undefined;
  hasPrevPage?: boolean | undefined;
  nextPageCursor?: string | undefined;
  perPage?: number | undefined;
  prevPageCursor?: string | undefined;
  total?: number | undefined;
};

export type GetSubscriptionsData = {
  content?: Array<models.ModelsSubscriptionResponse> | undefined;
  pagination?: GetSubscriptionsPagination | null | undefined;
};

/**
 * OK
 */
export type GetSubscriptionsResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: GetSubscriptionsData | undefined;
};

/** @internal */
export const GetSubscriptionsDirection$outboundSchema: z.ZodMiniEnum<
  typeof GetSubscriptionsDirection
> = z.enum(GetSubscriptionsDirection);

/** @internal */
export type GetSubscriptionsRequest$Outbound = {
  projectID: string;
  direction?: string | undefined;
  endpointId?: Array<string> | undefined;
  name?: string | undefined;
  next_page_cursor?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  sort?: string | undefined;
};

/** @internal */
export const GetSubscriptionsRequest$outboundSchema: z.ZodMiniType<
  GetSubscriptionsRequest$Outbound,
  GetSubscriptionsRequest
> = z.pipe(
  z.object({
    projectID: z.string(),
    direction: z.optional(GetSubscriptionsDirection$outboundSchema),
    endpointId: z.optional(z.array(z.string())),
    name: z.optional(z.string()),
    nextPageCursor: z.optional(z.string()),
    perPage: z.optional(z.int()),
    prevPageCursor: z.optional(z.string()),
    sort: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      nextPageCursor: "next_page_cursor",
      prevPageCursor: "prev_page_cursor",
    });
  }),
);

export function getSubscriptionsRequestToJSON(
  getSubscriptionsRequest: GetSubscriptionsRequest,
): string {
  return JSON.stringify(
    GetSubscriptionsRequest$outboundSchema.parse(getSubscriptionsRequest),
  );
}

/** @internal */
export const GetSubscriptionsPagination$inboundSchema: z.ZodMiniType<
  GetSubscriptionsPagination,
  unknown
> = z.pipe(
  z.object({
    has_next_page: types.optional(types.boolean()),
    has_prev_page: types.optional(types.boolean()),
    next_page_cursor: types.optional(types.string()),
    per_page: types.optional(types.number()),
    prev_page_cursor: types.optional(types.string()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_next_page": "hasNextPage",
      "has_prev_page": "hasPrevPage",
      "next_page_cursor": "nextPageCursor",
      "per_page": "perPage",
      "prev_page_cursor": "prevPageCursor",
    });
  }),
);

export function getSubscriptionsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetSubscriptionsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubscriptionsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubscriptionsPagination' from JSON`,
  );
}

/** @internal */
export const GetSubscriptionsData$inboundSchema: z.ZodMiniType<
  GetSubscriptionsData,
  unknown
> = z.object({
  content: types.optional(
    z.array(models.ModelsSubscriptionResponse$inboundSchema),
  ),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetSubscriptionsPagination$inboundSchema)),
  ),
});

export function getSubscriptionsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetSubscriptionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubscriptionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubscriptionsData' from JSON`,
  );
}

/** @internal */
export const GetSubscriptionsResponse$inboundSchema: z.ZodMiniType<
  GetSubscriptionsResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.lazy(() => GetSubscriptionsData$inboundSchema)),
});

export function getSubscriptionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSubscriptionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubscriptionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubscriptionsResponse' from JSON`,
  );
}
