/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d42f92badf42
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetFiltersRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Subscription ID
   */
  subscriptionID: string;
};

/**
 * OK
 */
export type GetFiltersResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<models.ModelsFilterResponse> | undefined;
};

/** @internal */
export type GetFiltersRequest$Outbound = {
  projectID: string;
  subscriptionID: string;
};

/** @internal */
export const GetFiltersRequest$outboundSchema: z.ZodMiniType<
  GetFiltersRequest$Outbound,
  GetFiltersRequest
> = z.object({
  projectID: z.string(),
  subscriptionID: z.string(),
});

export function getFiltersRequestToJSON(
  getFiltersRequest: GetFiltersRequest,
): string {
  return JSON.stringify(
    GetFiltersRequest$outboundSchema.parse(getFiltersRequest),
  );
}

/** @internal */
export const GetFiltersResponse$inboundSchema: z.ZodMiniType<
  GetFiltersResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.array(models.ModelsFilterResponse$inboundSchema)),
});

export function getFiltersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetFiltersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFiltersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFiltersResponse' from JSON`,
  );
}
