/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 689e3d7da694
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const GetMetaEventsPagedDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type GetMetaEventsPagedDirection = ClosedEnum<
  typeof GetMetaEventsPagedDirection
>;

export type GetMetaEventsPagedRequest = {
  /**
   * Project ID
   */
  projectID: string;
  direction?: GetMetaEventsPagedDirection | undefined;
  /**
   * The end date
   */
  endDate?: string | undefined;
  /**
   * A pagination cursor to fetch the next page of a list
   */
  nextPageCursor?: string | undefined;
  /**
   * The number of items to return per page
   */
  perPage?: number | undefined;
  /**
   * A pagination cursor to fetch the previous page of a list
   */
  prevPageCursor?: string | undefined;
  /**
   * Sort order, values are `ASC` or `DESC`, defaults to `DESC`
   */
  sort?: string | undefined;
  /**
   * The start date
   */
  startDate?: string | undefined;
};

export type GetMetaEventsPagedPagination = {
  hasNextPage?: boolean | undefined;
  hasPrevPage?: boolean | undefined;
  nextPageCursor?: string | undefined;
  perPage?: number | undefined;
  prevPageCursor?: string | undefined;
  total?: number | undefined;
};

export type GetMetaEventsPagedData = {
  content?: Array<models.ModelsMetaEventResponse> | undefined;
  pagination?: GetMetaEventsPagedPagination | null | undefined;
};

/**
 * OK
 */
export type GetMetaEventsPagedResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: GetMetaEventsPagedData | undefined;
};

/** @internal */
export const GetMetaEventsPagedDirection$outboundSchema: z.ZodMiniEnum<
  typeof GetMetaEventsPagedDirection
> = z.enum(GetMetaEventsPagedDirection);

/** @internal */
export type GetMetaEventsPagedRequest$Outbound = {
  projectID: string;
  direction?: string | undefined;
  endDate?: string | undefined;
  next_page_cursor?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  sort?: string | undefined;
  startDate?: string | undefined;
};

/** @internal */
export const GetMetaEventsPagedRequest$outboundSchema: z.ZodMiniType<
  GetMetaEventsPagedRequest$Outbound,
  GetMetaEventsPagedRequest
> = z.pipe(
  z.object({
    projectID: z.string(),
    direction: z.optional(GetMetaEventsPagedDirection$outboundSchema),
    endDate: z.optional(z.string()),
    nextPageCursor: z.optional(z.string()),
    perPage: z.optional(z.int()),
    prevPageCursor: z.optional(z.string()),
    sort: z.optional(z.string()),
    startDate: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      nextPageCursor: "next_page_cursor",
      prevPageCursor: "prev_page_cursor",
    });
  }),
);

export function getMetaEventsPagedRequestToJSON(
  getMetaEventsPagedRequest: GetMetaEventsPagedRequest,
): string {
  return JSON.stringify(
    GetMetaEventsPagedRequest$outboundSchema.parse(getMetaEventsPagedRequest),
  );
}

/** @internal */
export const GetMetaEventsPagedPagination$inboundSchema: z.ZodMiniType<
  GetMetaEventsPagedPagination,
  unknown
> = z.pipe(
  z.object({
    has_next_page: types.optional(types.boolean()),
    has_prev_page: types.optional(types.boolean()),
    next_page_cursor: types.optional(types.string()),
    per_page: types.optional(types.number()),
    prev_page_cursor: types.optional(types.string()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_next_page": "hasNextPage",
      "has_prev_page": "hasPrevPage",
      "next_page_cursor": "nextPageCursor",
      "per_page": "perPage",
      "prev_page_cursor": "prevPageCursor",
    });
  }),
);

export function getMetaEventsPagedPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetMetaEventsPagedPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMetaEventsPagedPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMetaEventsPagedPagination' from JSON`,
  );
}

/** @internal */
export const GetMetaEventsPagedData$inboundSchema: z.ZodMiniType<
  GetMetaEventsPagedData,
  unknown
> = z.object({
  content: types.optional(
    z.array(models.ModelsMetaEventResponse$inboundSchema),
  ),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetMetaEventsPagedPagination$inboundSchema)),
  ),
});

export function getMetaEventsPagedDataFromJSON(
  jsonString: string,
): SafeParseResult<GetMetaEventsPagedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMetaEventsPagedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMetaEventsPagedData' from JSON`,
  );
}

/** @internal */
export const GetMetaEventsPagedResponse$inboundSchema: z.ZodMiniType<
  GetMetaEventsPagedResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.lazy(() => GetMetaEventsPagedData$inboundSchema)),
});

export function getMetaEventsPagedResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetMetaEventsPagedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMetaEventsPagedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMetaEventsPagedResponse' from JSON`,
  );
}
