/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eff3bda4d685
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetProjectsRequest = {
  /**
   * Organisation ID
   */
  orgID: string;
};

/**
 * OK
 */
export type GetProjectsResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<models.ModelsProjectResponse> | undefined;
};

/** @internal */
export type GetProjectsRequest$Outbound = {
  orgID: string;
};

/** @internal */
export const GetProjectsRequest$outboundSchema: z.ZodMiniType<
  GetProjectsRequest$Outbound,
  GetProjectsRequest
> = z.object({
  orgID: z.string(),
});

export function getProjectsRequestToJSON(
  getProjectsRequest: GetProjectsRequest,
): string {
  return JSON.stringify(
    GetProjectsRequest$outboundSchema.parse(getProjectsRequest),
  );
}

/** @internal */
export const GetProjectsResponse$inboundSchema: z.ZodMiniType<
  GetProjectsResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.array(models.ModelsProjectResponse$inboundSchema)),
});

export function getProjectsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetProjectsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProjectsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProjectsResponse' from JSON`,
  );
}
