/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7b9756115751
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetEndpointEventRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * event id
   */
  eventID: string;
};

/**
 * OK
 */
export type GetEndpointEventResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsEventResponse | undefined;
};

/** @internal */
export type GetEndpointEventRequest$Outbound = {
  projectID: string;
  eventID: string;
};

/** @internal */
export const GetEndpointEventRequest$outboundSchema: z.ZodMiniType<
  GetEndpointEventRequest$Outbound,
  GetEndpointEventRequest
> = z.object({
  projectID: z.string(),
  eventID: z.string(),
});

export function getEndpointEventRequestToJSON(
  getEndpointEventRequest: GetEndpointEventRequest,
): string {
  return JSON.stringify(
    GetEndpointEventRequest$outboundSchema.parse(getEndpointEventRequest),
  );
}

/** @internal */
export const GetEndpointEventResponse$inboundSchema: z.ZodMiniType<
  GetEndpointEventResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsEventResponse$inboundSchema),
});

export function getEndpointEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetEndpointEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEndpointEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEndpointEventResponse' from JSON`,
  );
}
