/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8f77d6951ebf
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ImportOpenApiSpecRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * OpenAPI specification
   */
  body: models.ModelsImportOpenAPISpec;
};

/**
 * OK
 */
export type ImportOpenApiSpecResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<models.ModelsEventTypeResponse> | undefined;
};

/** @internal */
export type ImportOpenApiSpecRequest$Outbound = {
  projectID: string;
  body: models.ModelsImportOpenAPISpec$Outbound;
};

/** @internal */
export const ImportOpenApiSpecRequest$outboundSchema: z.ZodMiniType<
  ImportOpenApiSpecRequest$Outbound,
  ImportOpenApiSpecRequest
> = z.object({
  projectID: z.string(),
  body: models.ModelsImportOpenAPISpec$outboundSchema,
});

export function importOpenApiSpecRequestToJSON(
  importOpenApiSpecRequest: ImportOpenApiSpecRequest,
): string {
  return JSON.stringify(
    ImportOpenApiSpecRequest$outboundSchema.parse(importOpenApiSpecRequest),
  );
}

/** @internal */
export const ImportOpenApiSpecResponse$inboundSchema: z.ZodMiniType<
  ImportOpenApiSpecResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.array(models.ModelsEventTypeResponse$inboundSchema)),
});

export function importOpenApiSpecResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImportOpenApiSpecResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImportOpenApiSpecResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImportOpenApiSpecResponse' from JSON`,
  );
}
