/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 08133e076791
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const LoadPortalLinksPagedDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type LoadPortalLinksPagedDirection = ClosedEnum<
  typeof LoadPortalLinksPagedDirection
>;

export type LoadPortalLinksPagedRequest = {
  /**
   * Project ID
   */
  projectID: string;
  direction?: LoadPortalLinksPagedDirection | undefined;
  /**
   * A pagination cursor to fetch the next page of a list
   */
  nextPageCursor?: string | undefined;
  /**
   * The owner ID of the endpoint
   */
  ownerId?: string | undefined;
  /**
   * The number of items to return per page
   */
  perPage?: number | undefined;
  /**
   * A pagination cursor to fetch the previous page of a list
   */
  prevPageCursor?: string | undefined;
  /**
   * The name of the endpoint
   */
  q?: string | undefined;
  /**
   * Sort order, values are `ASC` or `DESC`, defaults to `DESC`
   */
  sort?: string | undefined;
};

export type LoadPortalLinksPagedPagination = {
  hasNextPage?: boolean | undefined;
  hasPrevPage?: boolean | undefined;
  nextPageCursor?: string | undefined;
  perPage?: number | undefined;
  prevPageCursor?: string | undefined;
  total?: number | undefined;
};

export type LoadPortalLinksPagedData = {
  content?: Array<models.DatastorePortalLinkResponse> | undefined;
  pagination?: LoadPortalLinksPagedPagination | null | undefined;
};

/**
 * OK
 */
export type LoadPortalLinksPagedResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: LoadPortalLinksPagedData | undefined;
};

/** @internal */
export const LoadPortalLinksPagedDirection$outboundSchema: z.ZodMiniEnum<
  typeof LoadPortalLinksPagedDirection
> = z.enum(LoadPortalLinksPagedDirection);

/** @internal */
export type LoadPortalLinksPagedRequest$Outbound = {
  projectID: string;
  direction?: string | undefined;
  next_page_cursor?: string | undefined;
  ownerId?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  q?: string | undefined;
  sort?: string | undefined;
};

/** @internal */
export const LoadPortalLinksPagedRequest$outboundSchema: z.ZodMiniType<
  LoadPortalLinksPagedRequest$Outbound,
  LoadPortalLinksPagedRequest
> = z.pipe(
  z.object({
    projectID: z.string(),
    direction: z.optional(LoadPortalLinksPagedDirection$outboundSchema),
    nextPageCursor: z.optional(z.string()),
    ownerId: z.optional(z.string()),
    perPage: z.optional(z.int()),
    prevPageCursor: z.optional(z.string()),
    q: z.optional(z.string()),
    sort: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      nextPageCursor: "next_page_cursor",
      prevPageCursor: "prev_page_cursor",
    });
  }),
);

export function loadPortalLinksPagedRequestToJSON(
  loadPortalLinksPagedRequest: LoadPortalLinksPagedRequest,
): string {
  return JSON.stringify(
    LoadPortalLinksPagedRequest$outboundSchema.parse(
      loadPortalLinksPagedRequest,
    ),
  );
}

/** @internal */
export const LoadPortalLinksPagedPagination$inboundSchema: z.ZodMiniType<
  LoadPortalLinksPagedPagination,
  unknown
> = z.pipe(
  z.object({
    has_next_page: types.optional(types.boolean()),
    has_prev_page: types.optional(types.boolean()),
    next_page_cursor: types.optional(types.string()),
    per_page: types.optional(types.number()),
    prev_page_cursor: types.optional(types.string()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_next_page": "hasNextPage",
      "has_prev_page": "hasPrevPage",
      "next_page_cursor": "nextPageCursor",
      "per_page": "perPage",
      "prev_page_cursor": "prevPageCursor",
    });
  }),
);

export function loadPortalLinksPagedPaginationFromJSON(
  jsonString: string,
): SafeParseResult<LoadPortalLinksPagedPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoadPortalLinksPagedPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoadPortalLinksPagedPagination' from JSON`,
  );
}

/** @internal */
export const LoadPortalLinksPagedData$inboundSchema: z.ZodMiniType<
  LoadPortalLinksPagedData,
  unknown
> = z.object({
  content: types.optional(
    z.array(models.DatastorePortalLinkResponse$inboundSchema),
  ),
  pagination: z.optional(
    z.nullable(z.lazy(() => LoadPortalLinksPagedPagination$inboundSchema)),
  ),
});

export function loadPortalLinksPagedDataFromJSON(
  jsonString: string,
): SafeParseResult<LoadPortalLinksPagedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoadPortalLinksPagedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoadPortalLinksPagedData' from JSON`,
  );
}

/** @internal */
export const LoadPortalLinksPagedResponse$inboundSchema: z.ZodMiniType<
  LoadPortalLinksPagedResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.lazy(() => LoadPortalLinksPagedData$inboundSchema)),
});

export function loadPortalLinksPagedResponseFromJSON(
  jsonString: string,
): SafeParseResult<LoadPortalLinksPagedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoadPortalLinksPagedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoadPortalLinksPagedResponse' from JSON`,
  );
}
