/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ff8b99d1e179
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const LoadSourcesPagedDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type LoadSourcesPagedDirection = ClosedEnum<
  typeof LoadSourcesPagedDirection
>;

export type LoadSourcesPagedRequest = {
  /**
   * Project ID
   */
  projectID: string;
  direction?: LoadSourcesPagedDirection | undefined;
  /**
   * A pagination cursor to fetch the next page of a list
   */
  nextPageCursor?: string | undefined;
  /**
   * The number of items to return per page
   */
  perPage?: number | undefined;
  /**
   * A pagination cursor to fetch the previous page of a list
   */
  prevPageCursor?: string | undefined;
  /**
   * The custom source provider e.g. twitter, shopify
   */
  provider?: string | undefined;
  /**
   * Sort order, values are `ASC` or `DESC`, defaults to `DESC`
   */
  sort?: string | undefined;
  /**
   * The source type e.g. http, pub_sub
   */
  type?: string | undefined;
};

export type LoadSourcesPagedPagination = {
  hasNextPage?: boolean | undefined;
  hasPrevPage?: boolean | undefined;
  nextPageCursor?: string | undefined;
  perPage?: number | undefined;
  prevPageCursor?: string | undefined;
  total?: number | undefined;
};

export type LoadSourcesPagedData = {
  content?: Array<models.ModelsSourceResponse> | undefined;
  pagination?: LoadSourcesPagedPagination | null | undefined;
};

/**
 * OK
 */
export type LoadSourcesPagedResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: LoadSourcesPagedData | undefined;
};

/** @internal */
export const LoadSourcesPagedDirection$outboundSchema: z.ZodMiniEnum<
  typeof LoadSourcesPagedDirection
> = z.enum(LoadSourcesPagedDirection);

/** @internal */
export type LoadSourcesPagedRequest$Outbound = {
  projectID: string;
  direction?: string | undefined;
  next_page_cursor?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  provider?: string | undefined;
  sort?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const LoadSourcesPagedRequest$outboundSchema: z.ZodMiniType<
  LoadSourcesPagedRequest$Outbound,
  LoadSourcesPagedRequest
> = z.pipe(
  z.object({
    projectID: z.string(),
    direction: z.optional(LoadSourcesPagedDirection$outboundSchema),
    nextPageCursor: z.optional(z.string()),
    perPage: z.optional(z.int()),
    prevPageCursor: z.optional(z.string()),
    provider: z.optional(z.string()),
    sort: z.optional(z.string()),
    type: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      nextPageCursor: "next_page_cursor",
      prevPageCursor: "prev_page_cursor",
    });
  }),
);

export function loadSourcesPagedRequestToJSON(
  loadSourcesPagedRequest: LoadSourcesPagedRequest,
): string {
  return JSON.stringify(
    LoadSourcesPagedRequest$outboundSchema.parse(loadSourcesPagedRequest),
  );
}

/** @internal */
export const LoadSourcesPagedPagination$inboundSchema: z.ZodMiniType<
  LoadSourcesPagedPagination,
  unknown
> = z.pipe(
  z.object({
    has_next_page: types.optional(types.boolean()),
    has_prev_page: types.optional(types.boolean()),
    next_page_cursor: types.optional(types.string()),
    per_page: types.optional(types.number()),
    prev_page_cursor: types.optional(types.string()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_next_page": "hasNextPage",
      "has_prev_page": "hasPrevPage",
      "next_page_cursor": "nextPageCursor",
      "per_page": "perPage",
      "prev_page_cursor": "prevPageCursor",
    });
  }),
);

export function loadSourcesPagedPaginationFromJSON(
  jsonString: string,
): SafeParseResult<LoadSourcesPagedPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoadSourcesPagedPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoadSourcesPagedPagination' from JSON`,
  );
}

/** @internal */
export const LoadSourcesPagedData$inboundSchema: z.ZodMiniType<
  LoadSourcesPagedData,
  unknown
> = z.object({
  content: types.optional(z.array(models.ModelsSourceResponse$inboundSchema)),
  pagination: z.optional(
    z.nullable(z.lazy(() => LoadSourcesPagedPagination$inboundSchema)),
  ),
});

export function loadSourcesPagedDataFromJSON(
  jsonString: string,
): SafeParseResult<LoadSourcesPagedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoadSourcesPagedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoadSourcesPagedData' from JSON`,
  );
}

/** @internal */
export const LoadSourcesPagedResponse$inboundSchema: z.ZodMiniType<
  LoadSourcesPagedResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(z.lazy(() => LoadSourcesPagedData$inboundSchema)),
});

export function loadSourcesPagedResponseFromJSON(
  jsonString: string,
): SafeParseResult<LoadSourcesPagedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoadSourcesPagedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoadSourcesPagedResponse' from JSON`,
  );
}
