/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1bb62959c27b
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResendEventDeliveryRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * event delivery id
   */
  eventDeliveryID: string;
};

/**
 * OK
 */
export type ResendEventDeliveryResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsEventDeliveryResponse | undefined;
};

/** @internal */
export type ResendEventDeliveryRequest$Outbound = {
  projectID: string;
  eventDeliveryID: string;
};

/** @internal */
export const ResendEventDeliveryRequest$outboundSchema: z.ZodMiniType<
  ResendEventDeliveryRequest$Outbound,
  ResendEventDeliveryRequest
> = z.object({
  projectID: z.string(),
  eventDeliveryID: z.string(),
});

export function resendEventDeliveryRequestToJSON(
  resendEventDeliveryRequest: ResendEventDeliveryRequest,
): string {
  return JSON.stringify(
    ResendEventDeliveryRequest$outboundSchema.parse(resendEventDeliveryRequest),
  );
}

/** @internal */
export const ResendEventDeliveryResponse$inboundSchema: z.ZodMiniType<
  ResendEventDeliveryResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsEventDeliveryResponse$inboundSchema),
});

export function resendEventDeliveryResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResendEventDeliveryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResendEventDeliveryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResendEventDeliveryResponse' from JSON`,
  );
}
