/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a8d3c516b948
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResendMetaEventRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * meta event id
   */
  metaEventID: string;
};

/**
 * OK
 */
export type ResendMetaEventResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsMetaEventResponse | undefined;
};

/** @internal */
export type ResendMetaEventRequest$Outbound = {
  projectID: string;
  metaEventID: string;
};

/** @internal */
export const ResendMetaEventRequest$outboundSchema: z.ZodMiniType<
  ResendMetaEventRequest$Outbound,
  ResendMetaEventRequest
> = z.object({
  projectID: z.string(),
  metaEventID: z.string(),
});

export function resendMetaEventRequestToJSON(
  resendMetaEventRequest: ResendMetaEventRequest,
): string {
  return JSON.stringify(
    ResendMetaEventRequest$outboundSchema.parse(resendMetaEventRequest),
  );
}

/** @internal */
export const ResendMetaEventResponse$inboundSchema: z.ZodMiniType<
  ResendMetaEventResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsMetaEventResponse$inboundSchema),
});

export function resendMetaEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResendMetaEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResendMetaEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResendMetaEventResponse' from JSON`,
  );
}
