/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f53925c0a935
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RevokePortalLinkRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * portal link id
   */
  portalLinkID: string;
};

/**
 * OK
 */
export type RevokePortalLinkResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.HandlersStub | undefined;
};

/** @internal */
export type RevokePortalLinkRequest$Outbound = {
  projectID: string;
  portalLinkID: string;
};

/** @internal */
export const RevokePortalLinkRequest$outboundSchema: z.ZodMiniType<
  RevokePortalLinkRequest$Outbound,
  RevokePortalLinkRequest
> = z.object({
  projectID: z.string(),
  portalLinkID: z.string(),
});

export function revokePortalLinkRequestToJSON(
  revokePortalLinkRequest: RevokePortalLinkRequest,
): string {
  return JSON.stringify(
    RevokePortalLinkRequest$outboundSchema.parse(revokePortalLinkRequest),
  );
}

/** @internal */
export const RevokePortalLinkResponse$inboundSchema: z.ZodMiniType<
  RevokePortalLinkResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.HandlersStub$inboundSchema),
});

export function revokePortalLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<RevokePortalLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokePortalLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokePortalLinkResponse' from JSON`,
  );
}
