/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d1d0c79fa78a
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type TestSubscriptionFunctionRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Function Details
   */
  body: models.ModelsFunctionRequest;
};

/**
 * OK
 */
export type TestSubscriptionFunctionResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsFunctionResponse | undefined;
};

/** @internal */
export type TestSubscriptionFunctionRequest$Outbound = {
  projectID: string;
  body: models.ModelsFunctionRequest$Outbound;
};

/** @internal */
export const TestSubscriptionFunctionRequest$outboundSchema: z.ZodMiniType<
  TestSubscriptionFunctionRequest$Outbound,
  TestSubscriptionFunctionRequest
> = z.object({
  projectID: z.string(),
  body: models.ModelsFunctionRequest$outboundSchema,
});

export function testSubscriptionFunctionRequestToJSON(
  testSubscriptionFunctionRequest: TestSubscriptionFunctionRequest,
): string {
  return JSON.stringify(
    TestSubscriptionFunctionRequest$outboundSchema.parse(
      testSubscriptionFunctionRequest,
    ),
  );
}

/** @internal */
export const TestSubscriptionFunctionResponse$inboundSchema: z.ZodMiniType<
  TestSubscriptionFunctionResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsFunctionResponse$inboundSchema),
});

export function testSubscriptionFunctionResponseFromJSON(
  jsonString: string,
): SafeParseResult<TestSubscriptionFunctionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TestSubscriptionFunctionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TestSubscriptionFunctionResponse' from JSON`,
  );
}
