/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 51a8b51d4ec3
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateSourceRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * source id
   */
  sourceID: string;
  /**
   * Source Details
   */
  body: models.ModelsUpdateSource;
};

/**
 * Accepted
 */
export type UpdateSourceResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsSourceResponse | undefined;
};

/** @internal */
export type UpdateSourceRequest$Outbound = {
  projectID: string;
  sourceID: string;
  body: models.ModelsUpdateSource$Outbound;
};

/** @internal */
export const UpdateSourceRequest$outboundSchema: z.ZodMiniType<
  UpdateSourceRequest$Outbound,
  UpdateSourceRequest
> = z.object({
  projectID: z.string(),
  sourceID: z.string(),
  body: models.ModelsUpdateSource$outboundSchema,
});

export function updateSourceRequestToJSON(
  updateSourceRequest: UpdateSourceRequest,
): string {
  return JSON.stringify(
    UpdateSourceRequest$outboundSchema.parse(updateSourceRequest),
  );
}

/** @internal */
export const UpdateSourceResponse$inboundSchema: z.ZodMiniType<
  UpdateSourceResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsSourceResponse$inboundSchema),
});

export function updateSourceResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSourceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSourceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSourceResponse' from JSON`,
  );
}
