/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 301ac4f9113f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateProjectRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Project Details
   */
  body: models.ModelsUpdateProject;
};

/**
 * Accepted
 */
export type UpdateProjectResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsProjectResponse | undefined;
};

/** @internal */
export type UpdateProjectRequest$Outbound = {
  projectID: string;
  body: models.ModelsUpdateProject$Outbound;
};

/** @internal */
export const UpdateProjectRequest$outboundSchema: z.ZodMiniType<
  UpdateProjectRequest$Outbound,
  UpdateProjectRequest
> = z.object({
  projectID: z.string(),
  body: models.ModelsUpdateProject$outboundSchema,
});

export function updateProjectRequestToJSON(
  updateProjectRequest: UpdateProjectRequest,
): string {
  return JSON.stringify(
    UpdateProjectRequest$outboundSchema.parse(updateProjectRequest),
  );
}

/** @internal */
export const UpdateProjectResponse$inboundSchema: z.ZodMiniType<
  UpdateProjectResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsProjectResponse$inboundSchema),
});

export function updateProjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProjectResponse' from JSON`,
  );
}
