/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b67eb1fc9629
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateEventTypeRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Event Type ID
   */
  eventTypeId: string;
  /**
   * Event Type Details
   */
  body: models.ModelsUpdateEventType;
};

/**
 * Created
 */
export type UpdateEventTypeResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsEventTypeResponse | undefined;
};

/** @internal */
export type UpdateEventTypeRequest$Outbound = {
  projectID: string;
  eventTypeId: string;
  body: models.ModelsUpdateEventType$Outbound;
};

/** @internal */
export const UpdateEventTypeRequest$outboundSchema: z.ZodMiniType<
  UpdateEventTypeRequest$Outbound,
  UpdateEventTypeRequest
> = z.object({
  projectID: z.string(),
  eventTypeId: z.string(),
  body: models.ModelsUpdateEventType$outboundSchema,
});

export function updateEventTypeRequestToJSON(
  updateEventTypeRequest: UpdateEventTypeRequest,
): string {
  return JSON.stringify(
    UpdateEventTypeRequest$outboundSchema.parse(updateEventTypeRequest),
  );
}

/** @internal */
export const UpdateEventTypeResponse$inboundSchema: z.ZodMiniType<
  UpdateEventTypeResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsEventTypeResponse$inboundSchema),
});

export function updateEventTypeResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEventTypeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEventTypeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEventTypeResponse' from JSON`,
  );
}
