/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e083d8b915a0
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateEndpointRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Endpoint ID
   */
  endpointID: string;
  /**
   * Endpoint Details
   */
  body: models.ModelsUpdateEndpoint;
};

/**
 * Accepted
 */
export type UpdateEndpointResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsEndpointResponse | undefined;
};

/** @internal */
export type UpdateEndpointRequest$Outbound = {
  projectID: string;
  endpointID: string;
  body: models.ModelsUpdateEndpoint$Outbound;
};

/** @internal */
export const UpdateEndpointRequest$outboundSchema: z.ZodMiniType<
  UpdateEndpointRequest$Outbound,
  UpdateEndpointRequest
> = z.object({
  projectID: z.string(),
  endpointID: z.string(),
  body: models.ModelsUpdateEndpoint$outboundSchema,
});

export function updateEndpointRequestToJSON(
  updateEndpointRequest: UpdateEndpointRequest,
): string {
  return JSON.stringify(
    UpdateEndpointRequest$outboundSchema.parse(updateEndpointRequest),
  );
}

/** @internal */
export const UpdateEndpointResponse$inboundSchema: z.ZodMiniType<
  UpdateEndpointResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsEndpointResponse$inboundSchema),
});

export function updateEndpointResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEndpointResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEndpointResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEndpointResponse' from JSON`,
  );
}
