/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aee7e45f6795
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateFilterRequest = {
  /**
   * Project ID
   */
  projectID: string;
  /**
   * Subscription ID
   */
  subscriptionID: string;
  /**
   * Filter ID
   */
  filterID: string;
  /**
   * Updated filter
   */
  body: models.ModelsUpdateFilterRequest;
};

/**
 * OK
 */
export type UpdateFilterResponse = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: models.ModelsFilterResponse | undefined;
};

/** @internal */
export type UpdateFilterRequest$Outbound = {
  projectID: string;
  subscriptionID: string;
  filterID: string;
  body: models.ModelsUpdateFilterRequest$Outbound;
};

/** @internal */
export const UpdateFilterRequest$outboundSchema: z.ZodMiniType<
  UpdateFilterRequest$Outbound,
  UpdateFilterRequest
> = z.object({
  projectID: z.string(),
  subscriptionID: z.string(),
  filterID: z.string(),
  body: models.ModelsUpdateFilterRequest$outboundSchema,
});

export function updateFilterRequestToJSON(
  updateFilterRequest: UpdateFilterRequest,
): string {
  return JSON.stringify(
    UpdateFilterRequest$outboundSchema.parse(updateFilterRequest),
  );
}

/** @internal */
export const UpdateFilterResponse$inboundSchema: z.ZodMiniType<
  UpdateFilterResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(types.boolean()),
  data: types.optional(models.ModelsFilterResponse$inboundSchema),
});

export function updateFilterResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateFilterResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateFilterResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateFilterResponse' from JSON`,
  );
}
