/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 189f09fe7142
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ConfigSignatureHeaderProvider = {
  XConvoySignature: "X-Convoy-Signature",
} as const;
export type ConfigSignatureHeaderProvider = ClosedEnum<
  typeof ConfigSignatureHeaderProvider
>;

/** @internal */
export const ConfigSignatureHeaderProvider$inboundSchema: z.ZodMiniEnum<
  typeof ConfigSignatureHeaderProvider
> = z.enum(ConfigSignatureHeaderProvider);
/** @internal */
export const ConfigSignatureHeaderProvider$outboundSchema: z.ZodMiniEnum<
  typeof ConfigSignatureHeaderProvider
> = ConfigSignatureHeaderProvider$inboundSchema;
