/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 83b1b482ee21
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreMetaEventType,
  DatastoreMetaEventType$inboundSchema,
} from "./datastore-meta-event-type.js";
import {
  DatastorePubSubConfig,
  DatastorePubSubConfig$inboundSchema,
} from "./datastore-pub-sub-config.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreMetaEventConfiguration = {
  eventType?: Array<string> | undefined;
  isEnabled?: boolean | undefined;
  pubSub?: DatastorePubSubConfig | undefined;
  secret?: string | undefined;
  type?: DatastoreMetaEventType | undefined;
  url?: string | undefined;
};

/** @internal */
export const DatastoreMetaEventConfiguration$inboundSchema: z.ZodMiniType<
  DatastoreMetaEventConfiguration,
  unknown
> = z.pipe(
  z.object({
    event_type: types.optional(z.array(types.string())),
    is_enabled: types.optional(types.boolean()),
    pub_sub: types.optional(DatastorePubSubConfig$inboundSchema),
    secret: types.optional(types.string()),
    type: types.optional(DatastoreMetaEventType$inboundSchema),
    url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
      "is_enabled": "isEnabled",
      "pub_sub": "pubSub",
    });
  }),
);

export function datastoreMetaEventConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreMetaEventConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreMetaEventConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreMetaEventConfiguration' from JSON`,
  );
}
