/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bee03d4e99a0
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreCustomResponse,
  DatastoreCustomResponse$inboundSchema,
} from "./datastore-custom-response.js";
import {
  DatastoreProviderConfig,
  DatastoreProviderConfig$inboundSchema,
} from "./datastore-provider-config.js";
import {
  DatastorePubSubConfig,
  DatastorePubSubConfig$inboundSchema,
} from "./datastore-pub-sub-config.js";
import {
  DatastoreSourceProvider,
  DatastoreSourceProvider$inboundSchema,
} from "./datastore-source-provider.js";
import {
  DatastoreSourceType,
  DatastoreSourceType$inboundSchema,
} from "./datastore-source-type.js";
import {
  DatastoreVerifierConfig,
  DatastoreVerifierConfig$inboundSchema,
} from "./datastore-verifier-config.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreSource = {
  bodyFunction?: string | undefined;
  createdAt?: string | undefined;
  customResponse?: DatastoreCustomResponse | undefined;
  deletedAt?: string | undefined;
  eventTypeLocation?: string | undefined;
  forwardHeaders?: Array<string> | undefined;
  headerFunction?: string | undefined;
  idempotencyKeys?: Array<string> | undefined;
  isDisabled?: boolean | undefined;
  maskId?: string | undefined;
  name?: string | undefined;
  projectId?: string | undefined;
  provider?: DatastoreSourceProvider | undefined;
  providerConfig?: DatastoreProviderConfig | undefined;
  pubSub?: DatastorePubSubConfig | undefined;
  type?: DatastoreSourceType | undefined;
  uid?: string | undefined;
  updatedAt?: string | undefined;
  url?: string | undefined;
  verifier?: DatastoreVerifierConfig | undefined;
};

/** @internal */
export const DatastoreSource$inboundSchema: z.ZodMiniType<
  DatastoreSource,
  unknown
> = z.pipe(
  z.object({
    body_function: types.optional(types.string()),
    created_at: types.optional(types.string()),
    custom_response: types.optional(DatastoreCustomResponse$inboundSchema),
    deleted_at: types.optional(types.string()),
    event_type_location: types.optional(types.string()),
    forward_headers: types.optional(z.array(types.string())),
    header_function: types.optional(types.string()),
    idempotency_keys: types.optional(z.array(types.string())),
    is_disabled: types.optional(types.boolean()),
    mask_id: types.optional(types.string()),
    name: types.optional(types.string()),
    project_id: types.optional(types.string()),
    provider: types.optional(DatastoreSourceProvider$inboundSchema),
    provider_config: types.optional(DatastoreProviderConfig$inboundSchema),
    pub_sub: types.optional(DatastorePubSubConfig$inboundSchema),
    type: types.optional(DatastoreSourceType$inboundSchema),
    uid: types.optional(types.string()),
    updated_at: types.optional(types.string()),
    url: types.optional(types.string()),
    verifier: types.optional(DatastoreVerifierConfig$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "body_function": "bodyFunction",
      "created_at": "createdAt",
      "custom_response": "customResponse",
      "deleted_at": "deletedAt",
      "event_type_location": "eventTypeLocation",
      "forward_headers": "forwardHeaders",
      "header_function": "headerFunction",
      "idempotency_keys": "idempotencyKeys",
      "is_disabled": "isDisabled",
      "mask_id": "maskId",
      "project_id": "projectId",
      "provider_config": "providerConfig",
      "pub_sub": "pubSub",
      "updated_at": "updatedAt",
    });
  }),
);

export function datastoreSourceFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreSource' from JSON`,
  );
}
