/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 48f7e00f67ae
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreMetaEventAttempt = {
  requestHttpHeader?: { [k: string]: string } | undefined;
  responseData?: string | undefined;
  responseHttpHeader?: { [k: string]: string } | undefined;
};

/** @internal */
export const DatastoreMetaEventAttempt$inboundSchema: z.ZodMiniType<
  DatastoreMetaEventAttempt,
  unknown
> = z.pipe(
  z.object({
    request_http_header: types.optional(z.record(z.string(), types.string())),
    response_data: types.optional(types.string()),
    response_http_header: types.optional(z.record(z.string(), types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_http_header": "requestHttpHeader",
      "response_data": "responseData",
      "response_http_header": "responseHttpHeader",
    });
  }),
);

export function datastoreMetaEventAttemptFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreMetaEventAttempt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreMetaEventAttempt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreMetaEventAttempt' from JSON`,
  );
}
