/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d64b422524db
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DatastoreDeliveryMode = {
  AtLeastOnce: "at_least_once",
  AtMostOnce: "at_most_once",
} as const;
export type DatastoreDeliveryMode = OpenEnum<typeof DatastoreDeliveryMode>;

/** @internal */
export const DatastoreDeliveryMode$inboundSchema: z.ZodMiniType<
  DatastoreDeliveryMode,
  unknown
> = openEnums.inboundSchema(DatastoreDeliveryMode);
/** @internal */
export const DatastoreDeliveryMode$outboundSchema: z.ZodMiniType<
  string,
  DatastoreDeliveryMode
> = openEnums.outboundSchema(DatastoreDeliveryMode);
