/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: edb5cb0e00e1
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DatastoreStrategyProvider = {
  Linear: "linear",
  Exponential: "exponential",
  Unknown: "",
} as const;
export type DatastoreStrategyProvider = OpenEnum<
  typeof DatastoreStrategyProvider
>;

/** @internal */
export const DatastoreStrategyProvider$inboundSchema: z.ZodMiniType<
  DatastoreStrategyProvider,
  unknown
> = openEnums.inboundSchema(DatastoreStrategyProvider);
/** @internal */
export const DatastoreStrategyProvider$outboundSchema: z.ZodMiniType<
  string,
  DatastoreStrategyProvider
> = openEnums.outboundSchema(DatastoreStrategyProvider);
