/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 93db038d1a33
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreStrategyProvider,
  DatastoreStrategyProvider$inboundSchema,
} from "./datastore-strategy-provider.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreMetadata = {
  /**
   * Data to be sent to endpoint.
   */
  data?: Array<number> | undefined;
  intervalSeconds?: number | undefined;
  maxRetrySeconds?: number | undefined;
  nextSendTime?: string | undefined;
  /**
   * NumTrials: number of times we have tried to deliver this Event to
   *
   * @remarks
   * an application
   */
  numTrials?: number | undefined;
  raw?: string | undefined;
  retryLimit?: number | undefined;
  strategy?: DatastoreStrategyProvider | undefined;
};

/** @internal */
export const DatastoreMetadata$inboundSchema: z.ZodMiniType<
  DatastoreMetadata,
  unknown
> = z.pipe(
  z.object({
    data: types.optional(z.array(types.number())),
    interval_seconds: types.optional(types.number()),
    max_retry_seconds: types.optional(types.number()),
    next_send_time: types.optional(types.string()),
    num_trials: types.optional(types.number()),
    raw: types.optional(types.string()),
    retry_limit: types.optional(types.number()),
    strategy: types.optional(DatastoreStrategyProvider$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "interval_seconds": "intervalSeconds",
      "max_retry_seconds": "maxRetrySeconds",
      "next_send_time": "nextSendTime",
      "num_trials": "numTrials",
      "retry_limit": "retryLimit",
    });
  }),
);

export function datastoreMetadataFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreMetadata' from JSON`,
  );
}
