/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 90a9ecd774bb
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreAmqpCredentials = {
  password?: string | undefined;
  user?: string | undefined;
};

/** @internal */
export const DatastoreAmqpCredentials$inboundSchema: z.ZodMiniType<
  DatastoreAmqpCredentials,
  unknown
> = z.object({
  password: types.optional(types.string()),
  user: types.optional(types.string()),
});

export function datastoreAmqpCredentialsFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreAmqpCredentials, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreAmqpCredentials$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreAmqpCredentials' from JSON`,
  );
}
