/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5e57b448ba12
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DatastoreSourceType = {
  Http: "http",
  RestApi: "rest_api",
  PubSub: "pub_sub",
  DbChangeStream: "db_change_stream",
  Unknown: "",
} as const;
export type DatastoreSourceType = OpenEnum<typeof DatastoreSourceType>;

/** @internal */
export const DatastoreSourceType$inboundSchema: z.ZodMiniType<
  DatastoreSourceType,
  unknown
> = openEnums.inboundSchema(DatastoreSourceType);
/** @internal */
export const DatastoreSourceType$outboundSchema: z.ZodMiniType<
  string,
  DatastoreSourceType
> = openEnums.outboundSchema(DatastoreSourceType);
