/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3815feafffad
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreGooglePubSubConfig = {
  projectId?: string | undefined;
  serviceAccount?: Array<number> | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const DatastoreGooglePubSubConfig$inboundSchema: z.ZodMiniType<
  DatastoreGooglePubSubConfig,
  unknown
> = z.pipe(
  z.object({
    project_id: types.optional(types.string()),
    service_account: types.optional(z.array(types.number())),
    subscription_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "project_id": "projectId",
      "service_account": "serviceAccount",
      "subscription_id": "subscriptionId",
    });
  }),
);

export function datastoreGooglePubSubConfigFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreGooglePubSubConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreGooglePubSubConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreGooglePubSubConfig' from JSON`,
  );
}
