/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 29a304e55ac2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreEncodingType,
  DatastoreEncodingType$inboundSchema,
} from "./datastore-encoding-type.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreSignatureVersion = {
  createdAt?: string | undefined;
  encoding?: DatastoreEncodingType | undefined;
  hash?: string | undefined;
  uid?: string | undefined;
};

/** @internal */
export const DatastoreSignatureVersion$inboundSchema: z.ZodMiniType<
  DatastoreSignatureVersion,
  unknown
> = z.pipe(
  z.object({
    created_at: types.optional(types.string()),
    encoding: types.optional(DatastoreEncodingType$inboundSchema),
    hash: types.optional(types.string()),
    uid: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function datastoreSignatureVersionFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreSignatureVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreSignatureVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreSignatureVersion' from JSON`,
  );
}
