/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f4ae18507c48
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreAlertConfiguration = {
  count?: number | undefined;
  threshold?: string | undefined;
};

/** @internal */
export const DatastoreAlertConfiguration$inboundSchema: z.ZodMiniType<
  DatastoreAlertConfiguration,
  unknown
> = z.object({
  count: types.optional(types.number()),
  threshold: types.optional(types.string()),
});

export function datastoreAlertConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreAlertConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreAlertConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreAlertConfiguration' from JSON`,
  );
}
