/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 906d319d0e51
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreEndpoint,
  DatastoreEndpoint$inboundSchema,
} from "./datastore-endpoint.js";
import {
  DatastorePortalAuthType,
  DatastorePortalAuthType$inboundSchema,
} from "./datastore-portal-auth-type.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastorePortalLinkResponse = {
  authKey?: string | undefined;
  authType?: DatastorePortalAuthType | undefined;
  canManageEndpoint?: boolean | undefined;
  createdAt?: string | undefined;
  deletedAt?: string | undefined;
  endpointCount?: number | undefined;
  endpoints?: Array<string> | undefined;
  endpointsMetadata?: Array<DatastoreEndpoint> | undefined;
  name?: string | undefined;
  ownerId?: string | undefined;
  projectId?: string | undefined;
  token?: string | undefined;
  uid?: string | undefined;
  updatedAt?: string | undefined;
  url?: string | undefined;
};

/** @internal */
export const DatastorePortalLinkResponse$inboundSchema: z.ZodMiniType<
  DatastorePortalLinkResponse,
  unknown
> = z.pipe(
  z.object({
    auth_key: types.optional(types.string()),
    auth_type: types.optional(DatastorePortalAuthType$inboundSchema),
    can_manage_endpoint: types.optional(types.boolean()),
    created_at: types.optional(types.string()),
    deleted_at: types.optional(types.string()),
    endpoint_count: types.optional(types.number()),
    endpoints: types.optional(z.array(types.string())),
    endpoints_metadata: types.optional(
      z.array(DatastoreEndpoint$inboundSchema),
    ),
    name: types.optional(types.string()),
    owner_id: types.optional(types.string()),
    project_id: types.optional(types.string()),
    token: types.optional(types.string()),
    uid: types.optional(types.string()),
    updated_at: types.optional(types.string()),
    url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "auth_key": "authKey",
      "auth_type": "authType",
      "can_manage_endpoint": "canManageEndpoint",
      "created_at": "createdAt",
      "deleted_at": "deletedAt",
      "endpoint_count": "endpointCount",
      "endpoints_metadata": "endpointsMetadata",
      "owner_id": "ownerId",
      "project_id": "projectId",
      "updated_at": "updatedAt",
    });
  }),
);

export function datastorePortalLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<DatastorePortalLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastorePortalLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastorePortalLinkResponse' from JSON`,
  );
}
