/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5b256ea70796
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreOAuth2FieldMapping = {
  /**
   * Field name for access token (e.g., "accessToken", "access_token", "token")
   */
  accessToken?: string | undefined;
  /**
   * Field name for expiry time (e.g., "expiresIn", "expires_in", "expiresAt")
   */
  expiresIn?: string | undefined;
  /**
   * Field name for token type (e.g., "tokenType", "token_type")
   */
  tokenType?: string | undefined;
};

/** @internal */
export const DatastoreOAuth2FieldMapping$inboundSchema: z.ZodMiniType<
  DatastoreOAuth2FieldMapping,
  unknown
> = z.pipe(
  z.object({
    access_token: types.optional(types.string()),
    expires_in: types.optional(types.string()),
    token_type: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_token": "accessToken",
      "expires_in": "expiresIn",
      "token_type": "tokenType",
    });
  }),
);

export function datastoreOAuth2FieldMappingFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreOAuth2FieldMapping, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreOAuth2FieldMapping$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreOAuth2FieldMapping' from JSON`,
  );
}
