/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 922fda62796e
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type DatastoreCreatePortalLinkRequest = {
  authType?: string | undefined;
  /**
   * Specify whether endpoint management can be done through the Portal Link UI
   */
  canManageEndpoint?: boolean | undefined;
  /**
   * Deprecated
   *
   * @remarks
   * IDs of endpoints in this portal link
   */
  endpoints?: Array<string> | undefined;
  /**
   * Portal Link Name
   */
  name?: string | undefined;
  /**
   * OwnerID, the portal link will inherit all the endpoints with this owner ID
   */
  ownerId?: string | undefined;
};

/** @internal */
export type DatastoreCreatePortalLinkRequest$Outbound = {
  auth_type?: string | undefined;
  can_manage_endpoint?: boolean | undefined;
  endpoints?: Array<string> | undefined;
  name?: string | undefined;
  owner_id?: string | undefined;
};

/** @internal */
export const DatastoreCreatePortalLinkRequest$outboundSchema: z.ZodMiniType<
  DatastoreCreatePortalLinkRequest$Outbound,
  DatastoreCreatePortalLinkRequest
> = z.pipe(
  z.object({
    authType: z.optional(z.string()),
    canManageEndpoint: z.optional(z.boolean()),
    endpoints: z.optional(z.array(z.string())),
    name: z.optional(z.string()),
    ownerId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      authType: "auth_type",
      canManageEndpoint: "can_manage_endpoint",
      ownerId: "owner_id",
    });
  }),
);

export function datastoreCreatePortalLinkRequestToJSON(
  datastoreCreatePortalLinkRequest: DatastoreCreatePortalLinkRequest,
): string {
  return JSON.stringify(
    DatastoreCreatePortalLinkRequest$outboundSchema.parse(
      datastoreCreatePortalLinkRequest,
    ),
  );
}
