/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c23cff2c46be
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DatastorePubSubType = {
  Sqs: "sqs",
  Google: "google",
  Kafka: "kafka",
  Amqp: "amqp",
} as const;
export type DatastorePubSubType = OpenEnum<typeof DatastorePubSubType>;

/** @internal */
export const DatastorePubSubType$inboundSchema: z.ZodMiniType<
  DatastorePubSubType,
  unknown
> = openEnums.inboundSchema(DatastorePubSubType);
/** @internal */
export const DatastorePubSubType$outboundSchema: z.ZodMiniType<
  string,
  DatastorePubSubType
> = openEnums.outboundSchema(DatastorePubSubType);
