/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 47a6a5c248a8
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreKafkaAuth,
  DatastoreKafkaAuth$inboundSchema,
} from "./datastore-kafka-auth.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreKafkaPubSubConfig = {
  auth?: DatastoreKafkaAuth | undefined;
  brokers?: Array<string> | undefined;
  consumerGroupId?: string | undefined;
  topicName?: string | undefined;
};

/** @internal */
export const DatastoreKafkaPubSubConfig$inboundSchema: z.ZodMiniType<
  DatastoreKafkaPubSubConfig,
  unknown
> = z.pipe(
  z.object({
    auth: types.optional(DatastoreKafkaAuth$inboundSchema),
    brokers: types.optional(z.array(types.string())),
    consumer_group_id: types.optional(types.string()),
    topic_name: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "consumer_group_id": "consumerGroupId",
      "topic_name": "topicName",
    });
  }),
);

export function datastoreKafkaPubSubConfigFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreKafkaPubSubConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreKafkaPubSubConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreKafkaPubSubConfig' from JSON`,
  );
}
