/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c500a7a40f2e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreEncodingType,
  DatastoreEncodingType$inboundSchema,
} from "./datastore-encoding-type.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreHMac = {
  encoding?: DatastoreEncodingType | undefined;
  hash?: string | undefined;
  header?: string | undefined;
  secret?: string | undefined;
};

/** @internal */
export const DatastoreHMac$inboundSchema: z.ZodMiniType<
  DatastoreHMac,
  unknown
> = z.object({
  encoding: types.optional(DatastoreEncodingType$inboundSchema),
  hash: types.optional(types.string()),
  header: types.optional(types.string()),
  secret: types.optional(types.string()),
});

export function datastoreHMacFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreHMac, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreHMac$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreHMac' from JSON`,
  );
}
