/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f09ec26afc22
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DatastoreVerifierType = {
  Noop: "noop",
  Hmac: "hmac",
  BasicAuth: "basic_auth",
  ApiKey: "api_key",
} as const;
export type DatastoreVerifierType = OpenEnum<typeof DatastoreVerifierType>;

/** @internal */
export const DatastoreVerifierType$inboundSchema: z.ZodMiniType<
  DatastoreVerifierType,
  unknown
> = openEnums.inboundSchema(DatastoreVerifierType);
/** @internal */
export const DatastoreVerifierType$outboundSchema: z.ZodMiniType<
  string,
  DatastoreVerifierType
> = openEnums.outboundSchema(DatastoreVerifierType);
