/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8f873f340740
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreAmqpPubSubConfig,
  DatastoreAmqpPubSubConfig$inboundSchema,
} from "./datastore-amqp-pub-sub-config.js";
import {
  DatastoreGooglePubSubConfig,
  DatastoreGooglePubSubConfig$inboundSchema,
} from "./datastore-google-pub-sub-config.js";
import {
  DatastoreKafkaPubSubConfig,
  DatastoreKafkaPubSubConfig$inboundSchema,
} from "./datastore-kafka-pub-sub-config.js";
import {
  DatastorePubSubType,
  DatastorePubSubType$inboundSchema,
} from "./datastore-pub-sub-type.js";
import {
  DatastoreSQSPubSubConfig,
  DatastoreSQSPubSubConfig$inboundSchema,
} from "./datastore-sqs-pub-sub-config.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastorePubSubConfig = {
  amqp?: DatastoreAmqpPubSubConfig | undefined;
  google?: DatastoreGooglePubSubConfig | undefined;
  kafka?: DatastoreKafkaPubSubConfig | undefined;
  sqs?: DatastoreSQSPubSubConfig | undefined;
  type?: DatastorePubSubType | undefined;
  workers?: number | undefined;
};

/** @internal */
export const DatastorePubSubConfig$inboundSchema: z.ZodMiniType<
  DatastorePubSubConfig,
  unknown
> = z.object({
  amqp: types.optional(DatastoreAmqpPubSubConfig$inboundSchema),
  google: types.optional(DatastoreGooglePubSubConfig$inboundSchema),
  kafka: types.optional(DatastoreKafkaPubSubConfig$inboundSchema),
  sqs: types.optional(DatastoreSQSPubSubConfig$inboundSchema),
  type: types.optional(DatastorePubSubType$inboundSchema),
  workers: types.optional(types.number()),
});

export function datastorePubSubConfigFromJSON(
  jsonString: string,
): SafeParseResult<DatastorePubSubConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastorePubSubConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastorePubSubConfig' from JSON`,
  );
}
