/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9469bef8810d
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreTwitterProviderConfig,
  DatastoreTwitterProviderConfig$inboundSchema,
} from "./datastore-twitter-provider-config.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreProviderConfig = {
  twitter?: DatastoreTwitterProviderConfig | undefined;
};

/** @internal */
export const DatastoreProviderConfig$inboundSchema: z.ZodMiniType<
  DatastoreProviderConfig,
  unknown
> = z.object({
  twitter: types.optional(DatastoreTwitterProviderConfig$inboundSchema),
});

export function datastoreProviderConfigFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreProviderConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreProviderConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreProviderConfig' from JSON`,
  );
}
