/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1f0c4c6eff76
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DatastorePortalAuthType = {
  RefreshToken: "refresh_token",
  StaticToken: "static_token",
  Unknown: "",
} as const;
export type DatastorePortalAuthType = OpenEnum<typeof DatastorePortalAuthType>;

/** @internal */
export const DatastorePortalAuthType$inboundSchema: z.ZodMiniType<
  DatastorePortalAuthType,
  unknown
> = openEnums.inboundSchema(DatastorePortalAuthType);
