/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3ca852a7dfed
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreDeviceStatus,
  DatastoreDeviceStatus$inboundSchema,
} from "./datastore-device-status.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DatastoreDevice = {
  createdAt?: string | undefined;
  deletedAt?: string | undefined;
  endpointId?: string | undefined;
  hostName?: string | undefined;
  lastSeenAt?: string | undefined;
  projectId?: string | undefined;
  status?: DatastoreDeviceStatus | undefined;
  uid?: string | undefined;
  updatedAt?: string | undefined;
};

/** @internal */
export const DatastoreDevice$inboundSchema: z.ZodMiniType<
  DatastoreDevice,
  unknown
> = z.pipe(
  z.object({
    created_at: types.optional(types.string()),
    deleted_at: types.optional(types.string()),
    endpoint_id: types.optional(types.string()),
    host_name: types.optional(types.string()),
    last_seen_at: types.optional(types.string()),
    project_id: types.optional(types.string()),
    status: types.optional(DatastoreDeviceStatus$inboundSchema),
    uid: types.optional(types.string()),
    updated_at: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "deleted_at": "deletedAt",
      "endpoint_id": "endpointId",
      "host_name": "hostName",
      "last_seen_at": "lastSeenAt",
      "project_id": "projectId",
      "updated_at": "updatedAt",
    });
  }),
);

export function datastoreDeviceFromJSON(
  jsonString: string,
): SafeParseResult<DatastoreDevice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatastoreDevice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatastoreDevice' from JSON`,
  );
}
