/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0dff5116814e
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DatastoreOAuth2ExpiryTimeUnit = {
  Seconds: "seconds",
  Milliseconds: "milliseconds",
  Minutes: "minutes",
  Hours: "hours",
  Unknown: "",
} as const;
export type DatastoreOAuth2ExpiryTimeUnit = OpenEnum<
  typeof DatastoreOAuth2ExpiryTimeUnit
>;

/** @internal */
export const DatastoreOAuth2ExpiryTimeUnit$inboundSchema: z.ZodMiniType<
  DatastoreOAuth2ExpiryTimeUnit,
  unknown
> = openEnums.inboundSchema(DatastoreOAuth2ExpiryTimeUnit);
