/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 916097976a24
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DatastoreOAuth2AuthenticationType = {
  SharedSecret: "shared_secret",
  ClientAssertion: "client_assertion",
  Unknown: "",
} as const;
export type DatastoreOAuth2AuthenticationType = OpenEnum<
  typeof DatastoreOAuth2AuthenticationType
>;

/** @internal */
export const DatastoreOAuth2AuthenticationType$inboundSchema: z.ZodMiniType<
  DatastoreOAuth2AuthenticationType,
  unknown
> = openEnums.inboundSchema(DatastoreOAuth2AuthenticationType);
