/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 00fc23632292
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type HandlersStub = {};

/** @internal */
export const HandlersStub$inboundSchema: z.ZodMiniType<HandlersStub, unknown> =
  z.object({});

export function handlersStubFromJSON(
  jsonString: string,
): SafeParseResult<HandlersStub, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HandlersStub$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HandlersStub' from JSON`,
  );
}
