/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e066b7f2f162
 */

import * as z from "zod/v4-mini";

export type ModelsRateLimitConfiguration = {
  count?: number | undefined;
  duration?: number | undefined;
};

/** @internal */
export type ModelsRateLimitConfiguration$Outbound = {
  count?: number | undefined;
  duration?: number | undefined;
};

/** @internal */
export const ModelsRateLimitConfiguration$outboundSchema: z.ZodMiniType<
  ModelsRateLimitConfiguration$Outbound,
  ModelsRateLimitConfiguration
> = z.object({
  count: z.optional(z.int()),
  duration: z.optional(z.int()),
});

export function modelsRateLimitConfigurationToJSON(
  modelsRateLimitConfiguration: ModelsRateLimitConfiguration,
): string {
  return JSON.stringify(
    ModelsRateLimitConfiguration$outboundSchema.parse(
      modelsRateLimitConfiguration,
    ),
  );
}
