/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5b22f188a61e
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ModelsGooglePubSubConfig = {
  projectId?: string | undefined;
  /**
   * encoding/json marshals []byte as a base64 string on the wire.
   */
  serviceAccount?: string | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export type ModelsGooglePubSubConfig$Outbound = {
  project_id?: string | undefined;
  service_account?: string | undefined;
  subscription_id?: string | undefined;
};

/** @internal */
export const ModelsGooglePubSubConfig$outboundSchema: z.ZodMiniType<
  ModelsGooglePubSubConfig$Outbound,
  ModelsGooglePubSubConfig
> = z.pipe(
  z.object({
    projectId: z.optional(z.string()),
    serviceAccount: z.optional(z.string()),
    subscriptionId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectId: "project_id",
      serviceAccount: "service_account",
      subscriptionId: "subscription_id",
    });
  }),
);

export function modelsGooglePubSubConfigToJSON(
  modelsGooglePubSubConfig: ModelsGooglePubSubConfig,
): string {
  return JSON.stringify(
    ModelsGooglePubSubConfig$outboundSchema.parse(modelsGooglePubSubConfig),
  );
}
