/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bc031a29e1a6
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ModelsBulkOnboardAcceptedResponse = {
  batchCount?: number | undefined;
  message?: string | undefined;
  totalItems?: number | undefined;
};

/** @internal */
export const ModelsBulkOnboardAcceptedResponse$inboundSchema: z.ZodMiniType<
  ModelsBulkOnboardAcceptedResponse,
  unknown
> = z.pipe(
  z.object({
    batch_count: types.optional(types.number()),
    message: types.optional(types.string()),
    total_items: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "batch_count": "batchCount",
      "total_items": "totalItems",
    });
  }),
);

export function modelsBulkOnboardAcceptedResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsBulkOnboardAcceptedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsBulkOnboardAcceptedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsBulkOnboardAcceptedResponse' from JSON`,
  );
}
