/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c092a6bbfc00
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  DatastoreSourceType,
  DatastoreSourceType$outboundSchema,
} from "./datastore-source-type.js";
import {
  ModelsPubSubConfig,
  ModelsPubSubConfig$Outbound,
  ModelsPubSubConfig$outboundSchema,
} from "./models-pub-sub-config.js";
import {
  ModelsUpdateCustomResponse,
  ModelsUpdateCustomResponse$Outbound,
  ModelsUpdateCustomResponse$outboundSchema,
} from "./models-update-custom-response.js";
import {
  ModelsVerifierConfig,
  ModelsVerifierConfig$Outbound,
  ModelsVerifierConfig$outboundSchema,
} from "./models-verifier-config.js";

export type ModelsUpdateSource = {
  /**
   * Function is a javascript function used to mutate the payload
   *
   * @remarks
   * immediately after ingesting an event
   */
  bodyFunction?: string | undefined;
  /**
   * Custom response is used to define a custom response for incoming
   *
   * @remarks
   * webhooks project sources only.
   */
  customResponse?: ModelsUpdateCustomResponse | undefined;
  /**
   * EventTypeLocation is used to specify where Convoy should read the event type
   *
   * @remarks
   * from an incoming webhook request.
   */
  eventTypeLocation?: string | undefined;
  /**
   * Soecfy header you want convoy to save from the ingest request and forward to your endpoints when the event is dispatched.
   */
  forwardHeaders?: Array<string> | undefined;
  /**
   * Function is a javascript function used to mutate the headers
   *
   * @remarks
   * immediately after ingesting an event
   */
  headerFunction?: string | undefined;
  /**
   * IdempotencyKeys are used to specify parts of a webhook request to uniquely
   *
   * @remarks
   * identify the event in an incoming webhooks project.
   */
  idempotencyKeys?: Array<string> | undefined;
  /**
   * This is used to manually enable/disable the source.
   */
  isDisabled?: boolean | undefined;
  /**
   * Source name.
   */
  name?: string | undefined;
  /**
   * PubSub are used to specify message broker sources for outgoing
   *
   * @remarks
   * webhooks projects, you only need to specify this when the source type is `pub_sub`.
   */
  pubSub?: ModelsPubSubConfig | undefined;
  /**
   * Source Type.
   */
  type?: DatastoreSourceType | undefined;
  /**
   * Verifiers are used to verify webhook events ingested in incoming
   *
   * @remarks
   * webhooks projects.  If set, type is required and match the verifier
   * type object you choose.
   */
  verifier?: ModelsVerifierConfig | undefined;
};

/** @internal */
export type ModelsUpdateSource$Outbound = {
  body_function?: string | undefined;
  custom_response?: ModelsUpdateCustomResponse$Outbound | undefined;
  event_type_location?: string | undefined;
  forward_headers?: Array<string> | undefined;
  header_function?: string | undefined;
  idempotency_keys?: Array<string> | undefined;
  is_disabled?: boolean | undefined;
  name?: string | undefined;
  pub_sub?: ModelsPubSubConfig$Outbound | undefined;
  type?: string | undefined;
  verifier?: ModelsVerifierConfig$Outbound | undefined;
};

/** @internal */
export const ModelsUpdateSource$outboundSchema: z.ZodMiniType<
  ModelsUpdateSource$Outbound,
  ModelsUpdateSource
> = z.pipe(
  z.object({
    bodyFunction: z.optional(z.string()),
    customResponse: z.optional(ModelsUpdateCustomResponse$outboundSchema),
    eventTypeLocation: z.optional(z.string()),
    forwardHeaders: z.optional(z.array(z.string())),
    headerFunction: z.optional(z.string()),
    idempotencyKeys: z.optional(z.array(z.string())),
    isDisabled: z.optional(z.boolean()),
    name: z.optional(z.string()),
    pubSub: z.optional(ModelsPubSubConfig$outboundSchema),
    type: z.optional(DatastoreSourceType$outboundSchema),
    verifier: z.optional(ModelsVerifierConfig$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      bodyFunction: "body_function",
      customResponse: "custom_response",
      eventTypeLocation: "event_type_location",
      forwardHeaders: "forward_headers",
      headerFunction: "header_function",
      idempotencyKeys: "idempotency_keys",
      isDisabled: "is_disabled",
      pubSub: "pub_sub",
    });
  }),
);

export function modelsUpdateSourceToJSON(
  modelsUpdateSource: ModelsUpdateSource,
): string {
  return JSON.stringify(
    ModelsUpdateSource$outboundSchema.parse(modelsUpdateSource),
  );
}
