/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 06188620a7d3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ModelsTestOAuth2Response = {
  accessToken?: string | undefined;
  error?: string | undefined;
  expiresAt?: string | undefined;
  message?: string | undefined;
  success?: boolean | undefined;
  tokenType?: string | undefined;
};

/** @internal */
export const ModelsTestOAuth2Response$inboundSchema: z.ZodMiniType<
  ModelsTestOAuth2Response,
  unknown
> = z.pipe(
  z.object({
    access_token: types.optional(types.string()),
    error: types.optional(types.string()),
    expires_at: types.optional(types.string()),
    message: types.optional(types.string()),
    success: types.optional(types.boolean()),
    token_type: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_token": "accessToken",
      "expires_at": "expiresAt",
      "token_type": "tokenType",
    });
  }),
);

export function modelsTestOAuth2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsTestOAuth2Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsTestOAuth2Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsTestOAuth2Response' from JSON`,
  );
}
