/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4cb269c4aaf8
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type JsonSchema = {};

export type ModelsEventTypeResponse = {
  category?: string | undefined;
  deprecatedAt?: string | undefined;
  description?: string | undefined;
  jsonSchema?: JsonSchema | undefined;
  name?: string | undefined;
  uid?: string | undefined;
};

/** @internal */
export const JsonSchema$inboundSchema: z.ZodMiniType<JsonSchema, unknown> = z
  .object({});

export function jsonSchemaFromJSON(
  jsonString: string,
): SafeParseResult<JsonSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JsonSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JsonSchema' from JSON`,
  );
}

/** @internal */
export const ModelsEventTypeResponse$inboundSchema: z.ZodMiniType<
  ModelsEventTypeResponse,
  unknown
> = z.pipe(
  z.object({
    category: types.optional(types.string()),
    deprecated_at: types.optional(types.string()),
    description: types.optional(types.string()),
    json_schema: types.optional(z.lazy(() => JsonSchema$inboundSchema)),
    name: types.optional(types.string()),
    uid: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "deprecated_at": "deprecatedAt",
      "json_schema": "jsonSchema",
    });
  }),
);

export function modelsEventTypeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsEventTypeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsEventTypeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsEventTypeResponse' from JSON`,
  );
}
