/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 704f2d881e25
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  DatastoreEndpointAuthenticationType,
  DatastoreEndpointAuthenticationType$outboundSchema,
} from "./datastore-endpoint-authentication-type.js";
import {
  ModelsApiKey,
  ModelsApiKey$Outbound,
  ModelsApiKey$outboundSchema,
} from "./models-api-key.js";
import {
  ModelsBasicAuth,
  ModelsBasicAuth$Outbound,
  ModelsBasicAuth$outboundSchema,
} from "./models-basic-auth.js";
import {
  ModelsOAuth2,
  ModelsOAuth2$Outbound,
  ModelsOAuth2$outboundSchema,
} from "./models-o-auth2.js";

export type ModelsEndpointAuthentication = {
  apiKey?: ModelsApiKey | undefined;
  basicAuth?: ModelsBasicAuth | undefined;
  oauth2?: ModelsOAuth2 | undefined;
  type?: DatastoreEndpointAuthenticationType | undefined;
};

/** @internal */
export type ModelsEndpointAuthentication$Outbound = {
  api_key?: ModelsApiKey$Outbound | undefined;
  basic_auth?: ModelsBasicAuth$Outbound | undefined;
  oauth2?: ModelsOAuth2$Outbound | undefined;
  type?: string | undefined;
};

/** @internal */
export const ModelsEndpointAuthentication$outboundSchema: z.ZodMiniType<
  ModelsEndpointAuthentication$Outbound,
  ModelsEndpointAuthentication
> = z.pipe(
  z.object({
    apiKey: z.optional(ModelsApiKey$outboundSchema),
    basicAuth: z.optional(ModelsBasicAuth$outboundSchema),
    oauth2: z.optional(ModelsOAuth2$outboundSchema),
    type: z.optional(DatastoreEndpointAuthenticationType$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKey: "api_key",
      basicAuth: "basic_auth",
    });
  }),
);

export function modelsEndpointAuthenticationToJSON(
  modelsEndpointAuthentication: ModelsEndpointAuthentication,
): string {
  return JSON.stringify(
    ModelsEndpointAuthentication$outboundSchema.parse(
      modelsEndpointAuthentication,
    ),
  );
}
