/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7535d114555a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreProjectConfig,
  DatastoreProjectConfig$inboundSchema,
} from "./datastore-project-config.js";
import {
  DatastoreProjectStatistics,
  DatastoreProjectStatistics$inboundSchema,
} from "./datastore-project-statistics.js";
import {
  DatastoreProjectType,
  DatastoreProjectType$inboundSchema,
} from "./datastore-project-type.js";
import {
  DatastoreRole,
  DatastoreRole$inboundSchema,
} from "./datastore-role.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiKey = {
  createdAt?: string | undefined;
  expiresAt?: string | undefined;
  key?: string | undefined;
  keyType?: string | undefined;
  name?: string | undefined;
  role?: DatastoreRole | undefined;
  uid?: string | undefined;
  userId?: string | undefined;
};

export type Project = {
  config?: DatastoreProjectConfig | undefined;
  createdAt?: string | undefined;
  deletedAt?: string | undefined;
  logoUrl?: string | undefined;
  name?: string | undefined;
  organisationId?: string | undefined;
  retainedEvents?: number | undefined;
  statistics?: DatastoreProjectStatistics | undefined;
  type?: DatastoreProjectType | undefined;
  uid?: string | undefined;
  updatedAt?: string | undefined;
};

export type ModelsCreateProjectResponse = {
  apiKey?: ApiKey | null | undefined;
  project?: Project | null | undefined;
};

/** @internal */
export const ApiKey$inboundSchema: z.ZodMiniType<ApiKey, unknown> = z.pipe(
  z.object({
    created_at: types.optional(types.string()),
    expires_at: types.optional(types.string()),
    key: types.optional(types.string()),
    key_type: types.optional(types.string()),
    name: types.optional(types.string()),
    role: types.optional(DatastoreRole$inboundSchema),
    uid: types.optional(types.string()),
    user_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "expires_at": "expiresAt",
      "key_type": "keyType",
      "user_id": "userId",
    });
  }),
);

export function apiKeyFromJSON(
  jsonString: string,
): SafeParseResult<ApiKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiKey' from JSON`,
  );
}

/** @internal */
export const Project$inboundSchema: z.ZodMiniType<Project, unknown> = z.pipe(
  z.object({
    config: types.optional(DatastoreProjectConfig$inboundSchema),
    created_at: types.optional(types.string()),
    deleted_at: types.optional(types.string()),
    logo_url: types.optional(types.string()),
    name: types.optional(types.string()),
    organisation_id: types.optional(types.string()),
    retained_events: types.optional(types.number()),
    statistics: types.optional(DatastoreProjectStatistics$inboundSchema),
    type: types.optional(DatastoreProjectType$inboundSchema),
    uid: types.optional(types.string()),
    updated_at: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "deleted_at": "deletedAt",
      "logo_url": "logoUrl",
      "organisation_id": "organisationId",
      "retained_events": "retainedEvents",
      "updated_at": "updatedAt",
    });
  }),
);

export function projectFromJSON(
  jsonString: string,
): SafeParseResult<Project, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Project$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Project' from JSON`,
  );
}

/** @internal */
export const ModelsCreateProjectResponse$inboundSchema: z.ZodMiniType<
  ModelsCreateProjectResponse,
  unknown
> = z.pipe(
  z.object({
    api_key: z.optional(z.nullable(z.lazy(() => ApiKey$inboundSchema))),
    project: z.optional(z.nullable(z.lazy(() => Project$inboundSchema))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "api_key": "apiKey",
    });
  }),
);

export function modelsCreateProjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsCreateProjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsCreateProjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsCreateProjectResponse' from JSON`,
  );
}
