/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 11c75d5209af
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ModelsOAuth2FieldMapping,
  ModelsOAuth2FieldMapping$Outbound,
  ModelsOAuth2FieldMapping$outboundSchema,
} from "./models-o-auth2-field-mapping.js";
import {
  ModelsOAuth2SigningKey,
  ModelsOAuth2SigningKey$Outbound,
  ModelsOAuth2SigningKey$outboundSchema,
} from "./models-o-auth2-signing-key.js";

export type ModelsOAuth2 = {
  audience?: string | undefined;
  authenticationType?: string | undefined;
  clientId?: string | undefined;
  clientSecret?: string | undefined;
  /**
   * Expiry time unit (seconds, milliseconds, minutes, hours)
   */
  expiryTimeUnit?: string | undefined;
  /**
   * Field mapping for flexible token response parsing
   */
  fieldMapping?: ModelsOAuth2FieldMapping | undefined;
  grantType?: string | undefined;
  issuer?: string | undefined;
  scope?: string | undefined;
  signingAlgorithm?: string | undefined;
  signingKey?: ModelsOAuth2SigningKey | undefined;
  subject?: string | undefined;
  url?: string | undefined;
};

/** @internal */
export type ModelsOAuth2$Outbound = {
  audience?: string | undefined;
  authentication_type?: string | undefined;
  client_id?: string | undefined;
  client_secret?: string | undefined;
  expiry_time_unit?: string | undefined;
  field_mapping?: ModelsOAuth2FieldMapping$Outbound | undefined;
  grant_type?: string | undefined;
  issuer?: string | undefined;
  scope?: string | undefined;
  signing_algorithm?: string | undefined;
  signing_key?: ModelsOAuth2SigningKey$Outbound | undefined;
  subject?: string | undefined;
  url?: string | undefined;
};

/** @internal */
export const ModelsOAuth2$outboundSchema: z.ZodMiniType<
  ModelsOAuth2$Outbound,
  ModelsOAuth2
> = z.pipe(
  z.object({
    audience: z.optional(z.string()),
    authenticationType: z.optional(z.string()),
    clientId: z.optional(z.string()),
    clientSecret: z.optional(z.string()),
    expiryTimeUnit: z.optional(z.string()),
    fieldMapping: z.optional(ModelsOAuth2FieldMapping$outboundSchema),
    grantType: z.optional(z.string()),
    issuer: z.optional(z.string()),
    scope: z.optional(z.string()),
    signingAlgorithm: z.optional(z.string()),
    signingKey: z.optional(ModelsOAuth2SigningKey$outboundSchema),
    subject: z.optional(z.string()),
    url: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      authenticationType: "authentication_type",
      clientId: "client_id",
      clientSecret: "client_secret",
      expiryTimeUnit: "expiry_time_unit",
      fieldMapping: "field_mapping",
      grantType: "grant_type",
      signingAlgorithm: "signing_algorithm",
      signingKey: "signing_key",
    });
  }),
);

export function modelsOAuth2ToJSON(modelsOAuth2: ModelsOAuth2): string {
  return JSON.stringify(ModelsOAuth2$outboundSchema.parse(modelsOAuth2));
}
