/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ecc1a15db660
 */

import * as z from "zod/v4-mini";

export type ModelsImportOpenAPISpec = {
  spec?: string | undefined;
};

/** @internal */
export type ModelsImportOpenAPISpec$Outbound = {
  spec?: string | undefined;
};

/** @internal */
export const ModelsImportOpenAPISpec$outboundSchema: z.ZodMiniType<
  ModelsImportOpenAPISpec$Outbound,
  ModelsImportOpenAPISpec
> = z.object({
  spec: z.optional(z.string()),
});

export function modelsImportOpenAPISpecToJSON(
  modelsImportOpenAPISpec: ModelsImportOpenAPISpec,
): string {
  return JSON.stringify(
    ModelsImportOpenAPISpec$outboundSchema.parse(modelsImportOpenAPISpec),
  );
}
