/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bb7bce34c6ad
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ModelsEndpointPeriodFailureRate = {
  failureCount?: number | undefined;
  periodFailureRate?: number | undefined;
  retryCount?: number | undefined;
  successCount?: number | undefined;
  uid?: string | undefined;
};

/** @internal */
export const ModelsEndpointPeriodFailureRate$inboundSchema: z.ZodMiniType<
  ModelsEndpointPeriodFailureRate,
  unknown
> = z.pipe(
  z.object({
    failure_count: types.optional(types.number()),
    period_failure_rate: types.optional(types.number()),
    retry_count: types.optional(types.number()),
    success_count: types.optional(types.number()),
    uid: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "failure_count": "failureCount",
      "period_failure_rate": "periodFailureRate",
      "retry_count": "retryCount",
      "success_count": "successCount",
    });
  }),
);

export function modelsEndpointPeriodFailureRateFromJSON(
  jsonString: string,
): SafeParseResult<ModelsEndpointPeriodFailureRate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsEndpointPeriodFailureRate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsEndpointPeriodFailureRate' from JSON`,
  );
}
