/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f528a8eaf1a5
 */

import * as z from "zod/v4-mini";

export type ModelsKafkaAuth = {
  hash?: string | undefined;
  password?: string | undefined;
  tls?: boolean | undefined;
  type?: string | undefined;
  username?: string | undefined;
};

/** @internal */
export type ModelsKafkaAuth$Outbound = {
  hash?: string | undefined;
  password?: string | undefined;
  tls?: boolean | undefined;
  type?: string | undefined;
  username?: string | undefined;
};

/** @internal */
export const ModelsKafkaAuth$outboundSchema: z.ZodMiniType<
  ModelsKafkaAuth$Outbound,
  ModelsKafkaAuth
> = z.object({
  hash: z.optional(z.string()),
  password: z.optional(z.string()),
  tls: z.optional(z.boolean()),
  type: z.optional(z.string()),
  username: z.optional(z.string()),
});

export function modelsKafkaAuthToJSON(
  modelsKafkaAuth: ModelsKafkaAuth,
): string {
  return JSON.stringify(ModelsKafkaAuth$outboundSchema.parse(modelsKafkaAuth));
}
