/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dd803d6ca556
 */

import * as z from "zod/v4-mini";
import {
  ModelsFilterSchema,
  ModelsFilterSchema$Outbound,
  ModelsFilterSchema$outboundSchema,
} from "./models-filter-schema.js";

export type ModelsTestFilter = {
  /**
   * Same Request & Headers
   */
  request?: ModelsFilterSchema | undefined;
  /**
   * Sample test schema
   */
  schema?: ModelsFilterSchema | undefined;
};

/** @internal */
export type ModelsTestFilter$Outbound = {
  request?: ModelsFilterSchema$Outbound | undefined;
  schema?: ModelsFilterSchema$Outbound | undefined;
};

/** @internal */
export const ModelsTestFilter$outboundSchema: z.ZodMiniType<
  ModelsTestFilter$Outbound,
  ModelsTestFilter
> = z.object({
  request: z.optional(ModelsFilterSchema$outboundSchema),
  schema: z.optional(ModelsFilterSchema$outboundSchema),
});

export function modelsTestFilterToJSON(
  modelsTestFilter: ModelsTestFilter,
): string {
  return JSON.stringify(
    ModelsTestFilter$outboundSchema.parse(modelsTestFilter),
  );
}
