/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c89181e96d60
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ModelsSSLConfiguration = {
  enforceSecureEndpoints?: boolean | undefined;
};

/** @internal */
export type ModelsSSLConfiguration$Outbound = {
  enforce_secure_endpoints?: boolean | undefined;
};

/** @internal */
export const ModelsSSLConfiguration$outboundSchema: z.ZodMiniType<
  ModelsSSLConfiguration$Outbound,
  ModelsSSLConfiguration
> = z.pipe(
  z.object({
    enforceSecureEndpoints: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      enforceSecureEndpoints: "enforce_secure_endpoints",
    });
  }),
);

export function modelsSSLConfigurationToJSON(
  modelsSSLConfiguration: ModelsSSLConfiguration,
): string {
  return JSON.stringify(
    ModelsSSLConfiguration$outboundSchema.parse(modelsSSLConfiguration),
  );
}
