/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 944945d5ec2e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ModelsOnboardValidationError = {
  field?: string | undefined;
  message?: string | undefined;
  row?: number | undefined;
};

/** @internal */
export const ModelsOnboardValidationError$inboundSchema: z.ZodMiniType<
  ModelsOnboardValidationError,
  unknown
> = z.object({
  field: types.optional(types.string()),
  message: types.optional(types.string()),
  row: types.optional(types.number()),
});

export function modelsOnboardValidationErrorFromJSON(
  jsonString: string,
): SafeParseResult<ModelsOnboardValidationError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsOnboardValidationError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsOnboardValidationError' from JSON`,
  );
}
