/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b476913c0756
 */

import * as z from "zod/v4-mini";
import {
  DatastoreEncodingType,
  DatastoreEncodingType$outboundSchema,
} from "./datastore-encoding-type.js";

export type ModelsHMac = {
  encoding: DatastoreEncodingType;
  hash: string;
  header: string;
  secret: string;
};

/** @internal */
export type ModelsHMac$Outbound = {
  encoding: string;
  hash: string;
  header: string;
  secret: string;
};

/** @internal */
export const ModelsHMac$outboundSchema: z.ZodMiniType<
  ModelsHMac$Outbound,
  ModelsHMac
> = z.object({
  encoding: DatastoreEncodingType$outboundSchema,
  hash: z.string(),
  header: z.string(),
  secret: z.string(),
});

export function modelsHMacToJSON(modelsHMac: ModelsHMac): string {
  return JSON.stringify(ModelsHMac$outboundSchema.parse(modelsHMac));
}
