/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 21fe9ff98dc0
 */

import * as z from "zod/v4-mini";

export type ModelsIDs = {
  /**
   * A list of event delivery IDs to forcefully resend.
   */
  ids?: Array<string> | undefined;
};

/** @internal */
export type ModelsIDs$Outbound = {
  ids?: Array<string> | undefined;
};

/** @internal */
export const ModelsIDs$outboundSchema: z.ZodMiniType<
  ModelsIDs$Outbound,
  ModelsIDs
> = z.object({
  ids: z.optional(z.array(z.string())),
});

export function modelsIDsToJSON(modelsIDs: ModelsIDs): string {
  return JSON.stringify(ModelsIDs$outboundSchema.parse(modelsIDs));
}
