/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c0aac602bf07
 */

import * as z from "zod/v4-mini";
import {
  ConfigSignatureHeaderProvider,
  ConfigSignatureHeaderProvider$outboundSchema,
} from "./config-signature-header-provider.js";
import {
  ModelsSignatureVersion,
  ModelsSignatureVersion$Outbound,
  ModelsSignatureVersion$outboundSchema,
} from "./models-signature-version.js";

export type ModelsSignatureConfiguration = {
  header?: ConfigSignatureHeaderProvider | undefined;
  versions?: Array<ModelsSignatureVersion> | undefined;
};

/** @internal */
export type ModelsSignatureConfiguration$Outbound = {
  header?: string | undefined;
  versions?: Array<ModelsSignatureVersion$Outbound> | undefined;
};

/** @internal */
export const ModelsSignatureConfiguration$outboundSchema: z.ZodMiniType<
  ModelsSignatureConfiguration$Outbound,
  ModelsSignatureConfiguration
> = z.object({
  header: z.optional(ConfigSignatureHeaderProvider$outboundSchema),
  versions: z.optional(z.array(ModelsSignatureVersion$outboundSchema)),
});

export function modelsSignatureConfigurationToJSON(
  modelsSignatureConfiguration: ModelsSignatureConfiguration,
): string {
  return JSON.stringify(
    ModelsSignatureConfiguration$outboundSchema.parse(
      modelsSignatureConfiguration,
    ),
  );
}
