/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4842d7e22256
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ModelsDynamicEvent = {
  /**
   * Specifies custom headers you want convoy to add when the event is dispatched to your endpoint
   */
  customHeaders?: { [k: string]: string } | undefined;
  /**
   * Data is an arbitrary JSON value that gets sent as the body of the
   *
   * @remarks
   * webhook to the endpoints
   */
  data?: { [k: string]: any } | undefined;
  /**
   * Event Type is used for filtering and debugging e.g invoice.paid
   */
  eventType?: string | undefined;
  /**
   * A list of event types for the subscription filter config
   */
  eventTypes?: Array<string> | undefined;
  /**
   * Specify a key for event deduplication
   */
  idempotencyKey?: string | undefined;
  /**
   * Endpoint's webhook secret. If not provided, Convoy autogenerates one for the endpoint.
   */
  secret?: string | undefined;
  /**
   * URL is the endpoint's URL prefixed with https. non-https urls are currently
   *
   * @remarks
   * not supported.
   */
  url?: string | undefined;
};

/** @internal */
export type ModelsDynamicEvent$Outbound = {
  custom_headers?: { [k: string]: string } | undefined;
  data?: { [k: string]: any } | undefined;
  event_type?: string | undefined;
  event_types?: Array<string> | undefined;
  idempotency_key?: string | undefined;
  secret?: string | undefined;
  url?: string | undefined;
};

/** @internal */
export const ModelsDynamicEvent$outboundSchema: z.ZodMiniType<
  ModelsDynamicEvent$Outbound,
  ModelsDynamicEvent
> = z.pipe(
  z.object({
    customHeaders: z.optional(z.record(z.string(), z.string())),
    data: z.optional(z.record(z.string(), z.any())),
    eventType: z.optional(z.string()),
    eventTypes: z.optional(z.array(z.string())),
    idempotencyKey: z.optional(z.string()),
    secret: z.optional(z.string()),
    url: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      customHeaders: "custom_headers",
      eventType: "event_type",
      eventTypes: "event_types",
      idempotencyKey: "idempotency_key",
    });
  }),
);

export function modelsDynamicEventToJSON(
  modelsDynamicEvent: ModelsDynamicEvent,
): string {
  return JSON.stringify(
    ModelsDynamicEvent$outboundSchema.parse(modelsDynamicEvent),
  );
}
