/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 04f1d45f6323
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ModelsMtlsClientCert = {
  /**
   * ClientCert is the client certificate PEM string
   */
  clientCert?: string | undefined;
  /**
   * ClientKey is the client private key PEM string
   */
  clientKey?: string | undefined;
};

/** @internal */
export type ModelsMtlsClientCert$Outbound = {
  client_cert?: string | undefined;
  client_key?: string | undefined;
};

/** @internal */
export const ModelsMtlsClientCert$outboundSchema: z.ZodMiniType<
  ModelsMtlsClientCert$Outbound,
  ModelsMtlsClientCert
> = z.pipe(
  z.object({
    clientCert: z.optional(z.string()),
    clientKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      clientCert: "client_cert",
      clientKey: "client_key",
    });
  }),
);

export function modelsMtlsClientCertToJSON(
  modelsMtlsClientCert: ModelsMtlsClientCert,
): string {
  return JSON.stringify(
    ModelsMtlsClientCert$outboundSchema.parse(modelsMtlsClientCert),
  );
}
