/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2503f345c1b2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ModelsOAuth2FieldMapping = {
  /**
   * Field name for access token (e.g., "accessToken", "access_token", "token")
   */
  accessToken?: string | undefined;
  /**
   * Field name for expiry time (e.g., "expiresIn", "expires_in", "expiresAt")
   */
  expiresIn?: string | undefined;
  /**
   * Field name for token type (e.g., "tokenType", "token_type")
   */
  tokenType?: string | undefined;
};

/** @internal */
export type ModelsOAuth2FieldMapping$Outbound = {
  access_token?: string | undefined;
  expires_in?: string | undefined;
  token_type?: string | undefined;
};

/** @internal */
export const ModelsOAuth2FieldMapping$outboundSchema: z.ZodMiniType<
  ModelsOAuth2FieldMapping$Outbound,
  ModelsOAuth2FieldMapping
> = z.pipe(
  z.object({
    accessToken: z.optional(z.string()),
    expiresIn: z.optional(z.string()),
    tokenType: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      accessToken: "access_token",
      expiresIn: "expires_in",
      tokenType: "token_type",
    });
  }),
);

export function modelsOAuth2FieldMappingToJSON(
  modelsOAuth2FieldMapping: ModelsOAuth2FieldMapping,
): string {
  return JSON.stringify(
    ModelsOAuth2FieldMapping$outboundSchema.parse(modelsOAuth2FieldMapping),
  );
}
