/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8bc2a28527a3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ModelsApiKey = {
  headerName: string;
  headerValue: string;
};

/** @internal */
export type ModelsApiKey$Outbound = {
  header_name: string;
  header_value: string;
};

/** @internal */
export const ModelsApiKey$outboundSchema: z.ZodMiniType<
  ModelsApiKey$Outbound,
  ModelsApiKey
> = z.pipe(
  z.object({
    headerName: z.string(),
    headerValue: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      headerName: "header_name",
      headerValue: "header_value",
    });
  }),
);

export function modelsApiKeyToJSON(modelsApiKey: ModelsApiKey): string {
  return JSON.stringify(ModelsApiKey$outboundSchema.parse(modelsApiKey));
}
