/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 98f105dce746
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  DatastoreStrategyProvider,
  DatastoreStrategyProvider$outboundSchema,
} from "./datastore-strategy-provider.js";

export type ModelsRetryConfiguration = {
  /**
   * Used to specify a valid Go time duration e.g 10s, 1h3m for how long to wait between event delivery retries
   */
  duration?: string | undefined;
  /**
   * Used to specify a time in seconds for how long to wait between event delivery retries,
   */
  intervalSeconds?: number | undefined;
  /**
   * Used to specify the max number of retries
   */
  retryCount?: number | undefined;
  /**
   * Retry Strategy type
   */
  type?: DatastoreStrategyProvider | undefined;
};

/** @internal */
export type ModelsRetryConfiguration$Outbound = {
  duration?: string | undefined;
  interval_seconds?: number | undefined;
  retry_count?: number | undefined;
  type?: string | undefined;
};

/** @internal */
export const ModelsRetryConfiguration$outboundSchema: z.ZodMiniType<
  ModelsRetryConfiguration$Outbound,
  ModelsRetryConfiguration
> = z.pipe(
  z.object({
    duration: z.optional(z.string()),
    intervalSeconds: z.optional(z.int()),
    retryCount: z.optional(z.int()),
    type: z.optional(DatastoreStrategyProvider$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      intervalSeconds: "interval_seconds",
      retryCount: "retry_count",
    });
  }),
);

export function modelsRetryConfigurationToJSON(
  modelsRetryConfiguration: ModelsRetryConfiguration,
): string {
  return JSON.stringify(
    ModelsRetryConfiguration$outboundSchema.parse(modelsRetryConfiguration),
  );
}
