/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f5d5ae06d75b
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DatastoreEventDeliveryStatus,
  DatastoreEventDeliveryStatus$inboundSchema,
} from "./datastore-event-delivery-status.js";
import {
  DatastoreMetaEventAttempt,
  DatastoreMetaEventAttempt$inboundSchema,
} from "./datastore-meta-event-attempt.js";
import {
  DatastoreMetadata,
  DatastoreMetadata$inboundSchema,
} from "./datastore-metadata.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ModelsMetaEventResponse = {
  attempt?: DatastoreMetaEventAttempt | undefined;
  createdAt?: string | undefined;
  deletedAt?: string | undefined;
  eventType?: string | undefined;
  metadata?: DatastoreMetadata | undefined;
  projectId?: string | undefined;
  status?: DatastoreEventDeliveryStatus | undefined;
  uid?: string | undefined;
  updatedAt?: string | undefined;
};

/** @internal */
export const ModelsMetaEventResponse$inboundSchema: z.ZodMiniType<
  ModelsMetaEventResponse,
  unknown
> = z.pipe(
  z.object({
    attempt: types.optional(DatastoreMetaEventAttempt$inboundSchema),
    created_at: types.optional(types.string()),
    deleted_at: types.optional(types.string()),
    event_type: types.optional(types.string()),
    metadata: types.optional(DatastoreMetadata$inboundSchema),
    project_id: types.optional(types.string()),
    status: types.optional(DatastoreEventDeliveryStatus$inboundSchema),
    uid: types.optional(types.string()),
    updated_at: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "deleted_at": "deletedAt",
      "event_type": "eventType",
      "project_id": "projectId",
      "updated_at": "updatedAt",
    });
  }),
);

export function modelsMetaEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsMetaEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsMetaEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsMetaEventResponse' from JSON`,
  );
}
