/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e75c52621b29
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ModelsProjectConfig,
  ModelsProjectConfig$Outbound,
  ModelsProjectConfig$outboundSchema,
} from "./models-project-config.js";

export type ModelsUpdateProject = {
  /**
   * Project Config
   */
  config?: ModelsProjectConfig | undefined;
  logoUrl?: string | undefined;
  /**
   * Project Name
   */
  name?: string | undefined;
};

/** @internal */
export type ModelsUpdateProject$Outbound = {
  config?: ModelsProjectConfig$Outbound | undefined;
  logo_url?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const ModelsUpdateProject$outboundSchema: z.ZodMiniType<
  ModelsUpdateProject$Outbound,
  ModelsUpdateProject
> = z.pipe(
  z.object({
    config: z.optional(ModelsProjectConfig$outboundSchema),
    logoUrl: z.optional(z.string()),
    name: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      logoUrl: "logo_url",
    });
  }),
);

export function modelsUpdateProjectToJSON(
  modelsUpdateProject: ModelsUpdateProject,
): string {
  return JSON.stringify(
    ModelsUpdateProject$outboundSchema.parse(modelsUpdateProject),
  );
}
