/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 284dae807cca
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ModelsFilterResponse = {
  body?: { [k: string]: any } | undefined;
  enabledAt?: string | undefined;
  eventType?: string | undefined;
  headers?: { [k: string]: any } | undefined;
  path?: { [k: string]: any } | undefined;
  query?: { [k: string]: any } | undefined;
  rawBody?: { [k: string]: any } | undefined;
  rawHeaders?: { [k: string]: any } | undefined;
  rawPath?: { [k: string]: any } | undefined;
  rawQuery?: { [k: string]: any } | undefined;
  subscriptionId?: string | undefined;
  uid?: string | undefined;
};

/** @internal */
export const ModelsFilterResponse$inboundSchema: z.ZodMiniType<
  ModelsFilterResponse,
  unknown
> = z.pipe(
  z.object({
    body: types.optional(z.record(z.string(), z.any())),
    enabled_at: types.optional(types.string()),
    event_type: types.optional(types.string()),
    headers: types.optional(z.record(z.string(), z.any())),
    path: types.optional(z.record(z.string(), z.any())),
    query: types.optional(z.record(z.string(), z.any())),
    raw_body: types.optional(z.record(z.string(), z.any())),
    raw_headers: types.optional(z.record(z.string(), z.any())),
    raw_path: types.optional(z.record(z.string(), z.any())),
    raw_query: types.optional(z.record(z.string(), z.any())),
    subscription_id: types.optional(types.string()),
    uid: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "enabled_at": "enabledAt",
      "event_type": "eventType",
      "raw_body": "rawBody",
      "raw_headers": "rawHeaders",
      "raw_path": "rawPath",
      "raw_query": "rawQuery",
      "subscription_id": "subscriptionId",
    });
  }),
);

export function modelsFilterResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsFilterResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsFilterResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsFilterResponse' from JSON`,
  );
}
