/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7f3b13d36c81
 */

import * as z from "zod/v4-mini";

export type ModelsOAuth2SigningKey = {
  /**
   * EC (Elliptic Curve) key fields
   */
  crv?: string | undefined;
  /**
   * Private key (EC) or private exponent (RSA)
   */
  d?: string | undefined;
  /**
   * RSA first factor CRT exponent (RSA private key only)
   */
  dp?: string | undefined;
  /**
   * RSA second factor CRT exponent (RSA private key only)
   */
  dq?: string | undefined;
  /**
   * RSA public exponent (RSA only)
   */
  e?: string | undefined;
  /**
   * Key ID
   */
  kid?: string | undefined;
  /**
   * Key type: "EC" or "RSA"
   */
  kty?: string | undefined;
  /**
   * RSA key fields
   */
  n?: string | undefined;
  /**
   * RSA first prime factor (RSA private key only)
   */
  p?: string | undefined;
  /**
   * RSA second prime factor (RSA private key only)
   */
  q?: string | undefined;
  /**
   * RSA first CRT coefficient (RSA private key only)
   */
  qi?: string | undefined;
  /**
   * X coordinate (EC only)
   */
  x?: string | undefined;
  /**
   * Y coordinate (EC only)
   */
  y?: string | undefined;
};

/** @internal */
export type ModelsOAuth2SigningKey$Outbound = {
  crv?: string | undefined;
  d?: string | undefined;
  dp?: string | undefined;
  dq?: string | undefined;
  e?: string | undefined;
  kid?: string | undefined;
  kty?: string | undefined;
  n?: string | undefined;
  p?: string | undefined;
  q?: string | undefined;
  qi?: string | undefined;
  x?: string | undefined;
  y?: string | undefined;
};

/** @internal */
export const ModelsOAuth2SigningKey$outboundSchema: z.ZodMiniType<
  ModelsOAuth2SigningKey$Outbound,
  ModelsOAuth2SigningKey
> = z.object({
  crv: z.optional(z.string()),
  d: z.optional(z.string()),
  dp: z.optional(z.string()),
  dq: z.optional(z.string()),
  e: z.optional(z.string()),
  kid: z.optional(z.string()),
  kty: z.optional(z.string()),
  n: z.optional(z.string()),
  p: z.optional(z.string()),
  q: z.optional(z.string()),
  qi: z.optional(z.string()),
  x: z.optional(z.string()),
  y: z.optional(z.string()),
});

export function modelsOAuth2SigningKeyToJSON(
  modelsOAuth2SigningKey: ModelsOAuth2SigningKey,
): string {
  return JSON.stringify(
    ModelsOAuth2SigningKey$outboundSchema.parse(modelsOAuth2SigningKey),
  );
}
