/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8b52c5998f56
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ModelsEventQueuedResponse = {
  eventType?: string | undefined;
  idempotencyKey?: string | undefined;
  /**
   * UID is the event id.
   */
  uid?: string | undefined;
};

/** @internal */
export const ModelsEventQueuedResponse$inboundSchema: z.ZodMiniType<
  ModelsEventQueuedResponse,
  unknown
> = z.pipe(
  z.object({
    event_type: types.optional(types.string()),
    idempotency_key: types.optional(types.string()),
    uid: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
      "idempotency_key": "idempotencyKey",
    });
  }),
);

export function modelsEventQueuedResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsEventQueuedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsEventQueuedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsEventQueuedResponse' from JSON`,
  );
}
