/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f2018847332c
 */

import * as z from "zod/v4-mini";

export type ModelsAlertConfiguration = {
  /**
   * Count
   */
  count?: number | undefined;
  /**
   * Threshold
   */
  threshold?: string | undefined;
};

/** @internal */
export type ModelsAlertConfiguration$Outbound = {
  count?: number | undefined;
  threshold?: string | undefined;
};

/** @internal */
export const ModelsAlertConfiguration$outboundSchema: z.ZodMiniType<
  ModelsAlertConfiguration$Outbound,
  ModelsAlertConfiguration
> = z.object({
  count: z.optional(z.int()),
  threshold: z.optional(z.string()),
});

export function modelsAlertConfigurationToJSON(
  modelsAlertConfiguration: ModelsAlertConfiguration,
): string {
  return JSON.stringify(
    ModelsAlertConfiguration$outboundSchema.parse(modelsAlertConfiguration),
  );
}
