/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2887637c4829
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ModelsTestFilterResponse = {
  /**
   * Whether the payload matches the filter criteria
   */
  isMatch?: boolean | undefined;
};

/** @internal */
export const ModelsTestFilterResponse$inboundSchema: z.ZodMiniType<
  ModelsTestFilterResponse,
  unknown
> = z.pipe(
  z.object({
    is_match: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_match": "isMatch",
    });
  }),
);

export function modelsTestFilterResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsTestFilterResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsTestFilterResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsTestFilterResponse' from JSON`,
  );
}
